-- S2U-35 --
CREATE TABLE COND_CONDITION (
  ID varchar2(36) NOT NULL,
  TYPE varchar2(99) NOT NULL,
  OPERATOR varchar2(99) DEFAULT NULL,
  ARGUMENT varchar2(999) DEFAULT NULL,
  SITE_ID varchar2(36) NOT NULL,
  TOOL_ID varchar2(99) NOT NULL,
  ITEM_ID varchar2(99) DEFAULT NULL,
  PRIMARY KEY (ID)
);
CREATE INDEX IDX_CONDITION_SITE_ID ON COND_CONDITION (SITE_ID);

CREATE TABLE COND_PARENT_CHILD (
  PARENT_ID varchar2(36) NOT NULL,
  CHILD_ID varchar2(36) NOT NULL,
  PRIMARY KEY (PARENT_ID, CHILD_ID),
  CONSTRAINT FK_CHILD_ID_CONDITION_ID FOREIGN KEY (CHILD_ID) REFERENCES COND_CONDITION (ID),
  CONSTRAINT FK_PARENT_ID_CONDITION_ID FOREIGN KEY (PARENT_ID) REFERENCES COND_CONDITION (ID)
);
CREATE INDEX FK_CHILD_ID_CONDITION_ID ON COND_PARENT_CHILD (CHILD_ID);
-- END S2U-35 --
