-- S2U-16 --
ALTER TABLE SAM_ITEMGRADING_T ADD COLUMN ATTEMPTDATE DATETIME NULL;

CREATE TABLE SAM_SECTIONGRADING_T (
  SECTIONGRADINGID NUMBER(19) NOT NULL,
  ASSESSMENTGRADINGID NUMBER(19) NOT NULL,
  PUBLISHEDSECTIONID NUMBER(19) NOT NULL,
  AGENTID VARCHAR2(255) NOT NULL,
  ATTEMPTDATE TIMESTAMP(6) DEFAULT NULL,
  PRIMARY KEY (SECTIONGRADINGID),
  CONSTRAINT uniqueStudentSectionResponse UNIQUE  (ASSESSMENTGRADINGID,PUBLISHEDSECTIONID,AGENTID)
);
CREATE SEQUENCE SAM_SECTIONGRADING_T_SEQ START WITH 1 INCREMENT BY 1;
-- S2U-16 --
