-- S2U-16 --
ALTER TABLE sam_itemgrading_t ADD COLUMN ATTEMPTDATE DATETIME NULL;

CREATE TABLE sam_sectiongrading_t (
  SECTIONGRADINGID number(19) NOT NULL,
  ASSESSMENTGRADINGID number(19) NOT NULL,
  PUBLISHEDSECTIONID number(19) NOT NULL,
  AGENTID varchar2(255) NOT NULL,
  ATTEMPTDATE timestamp(6) DEFAULT NULL,
  PRIMARY KEY (SECTIONGRADINGID),
  CONSTRAINT uniqueStudentSectionResponse UNIQUE  (ASSESSMENTGRADINGID,PUBLISHEDSECTIONID,AGENTID)
);
CREATE SEQUENCE sam_sectiongrading_t_seq START WITH 1 INCREMENT BY 1;
-- S2U-16 --