-- S2U-42 --
CREATE TABLE CARDGAME_STAT_ITEM (
  ID VARCHAR(99) PRIMARY KEY,
  PLAYER_ID VARCHAR(99) NOT NULL,
  USER_ID VARCHAR(99) NOT NULL,
  HITS INT NOT NULL,
  MISSES INT NOT NULL,
  MARKED_AS_LEARNED BIT(1) NOT NULL
);

CREATE INDEX IDX_CARDGAME_STAT_ITEM_PLAYER_ID ON CARDGAME_STAT_ITEM (ID, PLAYER_ID);
-- END S2U-42 --
