-- S2U-11 --
ALTER TABLE SAM_ITEMTEXT_T ADD ADDEDBUTNOTEXTRACTED NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE SAM_PUBLISHEDITEMTEXT_T ADD ADDEDBUTNOTEXTRACTED NUMBER(1,0) DEFAULT 0 NOT NULL;
-- End S2U-11 --