-- S2U-42 --
CREATE TABLE CARDGAME_STAT_ITEM (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PLAYER_ID VARCHAR(99) NOT NULL,
  USER_ID VARCHAR(99) NOT NULL,
  HITS INT DEFAULT 0 NULL,
  MISSES INT DEFAULT 0 NULL
);

CREATE INDEX IDX_CARDGAME_STAT_ITEM_PLAYER_ID ON CARDGAME_STAT_ITEM (ID, PLAYER_ID);
-- END S2U-42 --
