-- S2U-16 --
ALTER TABLE `SAM_ITEMGRADING_T` ADD COLUMN `ATTEMPTDATE` DATETIME NULL;

CREATE TABLE `SAM_SECTIONGRADING_T` (
  `SECTIONGRADINGID` bigint NOT NULL AUTO_INCREMENT,
  `ASSESSMENTGRADINGID` bigint NOT NULL,
  `PUBLISHEDSECTIONID` bigint NOT NULL,
  `AGENTID` varchar(255) NOT NULL,
  `ATTEMPTDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`SECTIONGRADINGID`),
  UNIQUE KEY `uniqueStudentSectionResponse` (`ASSESSMENTGRADINGID`,`PUBLISHEDSECTIONID`,`AGENTID`)
);
-- S2U-16 --
