-- S2U-16 --
ALTER TABLE `sam_itemgrading_t` ADD COLUMN `ATTEMPTDATE` DATETIME NULL;


CREATE TABLE `sam_sectiongrading_t` (
  `SECTIONGRADINGID` bigint NOT NULL AUTO_INCREMENT,
  `ASSESSMENTGRADINGID` bigint NOT NULL,
  `PUBLISHEDSECTIONID` bigint NOT NULL,
  `AGENTID` varchar(255) NOT NULL,
  `ATTEMPTDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`SECTIONGRADINGID`),
  UNIQUE KEY `uniqueStudentSectionResponse` (`ASSESSMENTGRADINGID`,`PUBLISHEDSECTIONID`,`AGENTID`)
);
-- S2U-16 --