
-- SAK-51949
ALTER TABLE CONTENT_RESOURCE DROP COLUMN XML;
ALTER TABLE CONTENT_RESOURCE_DELETE DROP COLUMN XML;
-- END SAK-51949

-- SAK-52193

-- Not used anymore
DROP TABLE PROFILE_EXTERNAL_INTEGRATION_T;
DROP TABLE PROFILE_IMAGES_EXTERNAL_T;

-- Not allowing multiple uploaded avatars at once
DELETE FROM PROFILE_IMAGES_T WHERE IS_CURRENT = 0;
ALTER TABLE PROFILE_IMAGES_T DROP INDEX PROFILE_IMAGES_IS_CURRENT_I;
ALTER TABLE PROFILE_IMAGES_T DROP COLUMN IS_CURRENT;

-- Using USER_UUID as the primary key
ALTER TABLE PROFILE_IMAGES_T DROP COLUMN ID;
ALTER TABLE PROFILE_IMAGES_T ADD PRIMARY KEY (USER_UUID);
ALTER TABLE PROFILE_IMAGES_T DROP INDEX PROFILE_IMAGES_USER_UUID_I;

-- END SAK-52193

-- START SAK-49440
ALTER TABLE mfr_permission_level_t CHANGE COLUMN MARK_AS_READ MARK_AS_NOT_READ bit(1) NOT NULL;
-- END SAK-49440

-- START SAK-52355
ALTER TABLE MC_SITE_SYNCHRONIZATION ADD DISABLED BIT DEFAULT b'0' NOT NULL;
-- END SAK-52355

-- START SAK-52495
ALTER TABLE GB_GRADABLE_OBJECT_T ADD COLUMN LINEITEM_METADATA LONGTEXT;
-- END SAK-52495

-- START SAK-52583
ALTER TABLE lti_tools ADD COLUMN allowgradebookreadonly TINYINT DEFAULT 0;
-- END SAK-52583
