-- SAK-44420
UPDATE poll_option SET deleted = 0 WHERE DELETED IS NULL;
ALTER TABLE poll_option MODIFY COLUMN DELETED BIT NOT NULL DEFAULT 0;
-- End SAK-44420

-- SAK-43497
alter table ASN_ASSIGNMENT_PROPERTIES modify VALUE varchar(4000) null;
-- END SAK-43407
