-- SAK-38427

ALTER TABLE MFR_TOPIC_T ADD ALLOW_EMAIL_NOTIFICATIONS NUMBER(1,0) DEFAULT 1 NOT NULL;
ALTER TABLE MFR_TOPIC_T ADD INCLUDE_CONTENTS_IN_EMAILS NUMBER(1,0) DEFAULT 1 NOT NULL;

-- END SAK-38427

-- SAK-33969
ALTER TABLE MFR_OPEN_FORUM_T ADD RESTRICT_PERMS_FOR_GROUPS NUMBER(1) DEFAULT '0';
ALTER TABLE MFR_TOPIC_T ADD RESTRICT_PERMS_FOR_GROUPS NUMBER(1) DEFAULT '0';
-- SAK-33969

-- SAK-39967

CREATE INDEX contentreview_provider_id_idx on CONTENTREVIEW_ITEM (providerId, externalId);

-- End SAK-39967

-- SAK-40182
DECLARE
    seq_start INTEGER;
BEGIN
   SELECT NVL(MAX(PUBLISHEDSECTIONMETADATAID),0) + 1
   INTO   seq_start   FROM SAM_PUBLISHEDSECTIONMETADATA_T;
   EXECUTE IMMEDIATE 'CREATE SEQUENCE SAM_PUBSECTIONMETADATA_ID_S START WITH '||seq_start||' INCREMENT BY 1 NOMAXVALUE';
END;
-- End SAK-40182

-- SAK-40721
ALTER TABLE BULLHORN_ALERTS ADD DEFERRED NUMBER(1) DEFAULT 0 NOT NULL;
-- END SAK-40721

-- SAK-41017

UPDATE SAKAI_SITE_PAGE SET layout = '0' WHERE page_id = '!error-100';
UPDATE SAKAI_SITE_PAGE SET layout = '0' WHERE page_id = '!urlError-100';

-- End of SAK-41017

-- BEGIN SAK-41172
CREATE TABLE SAKAI_GROUP_LOCK 
(
    GROUP_ID VARCHAR2(99) NOT NULL,
    ITEM_ID VARCHAR2(200) NOT NULL,
    LOCK_MODE VARCHAR2(32) NOT NULL,
    CONSTRAINT SAKAI_GROUP_LOCK_PK PRIMARY KEY (GROUP_ID, ITEM_ID, LOCK_MODE) ENABLE
);
-- END SAK-41172

-- BEGIN SAK-41219
DELETE FROM SAKAI_GROUP_LOCK;
INSERT INTO SAKAI_GROUP_LOCK (GROUP_ID, ITEM_ID, LOCK_MODE)
    SELECT GROUP_ID, TRIM(COLUMN_VALUE) VALUE, 'MODIFY'
    FROM SAKAI_SITE_GROUP_PROPERTY,
         XMLTABLE(('"' || REPLACE(VALUE, '#:#', '","') || '"'))
    WHERE NAME ='group_prop_locked_by';
/*Execute at your own risk, cleans up the rows of sakai_site_group_property after moving them to the new table.*/
/*DELETE FROM SAKAI_SITE_GROUP_PROPERTY WHERE NAME ='group_prop_locked_by';*/
-- END SAK-41219
