
-- START SAK-51950
CREATE INDEX CAL_EVENT_CID_RST_REND_EST
  ON CALENDAR_EVENT (CALENDAR_ID, RANGE_START, RANGE_END, EVENT_START);
-- END SAK-51950

-- START SAK-49313
ALTER TABLE SAM_PUBLISHEDASSESSMENT_T MODIFY (COMMENTS VARCHAR2(4000));
-- END SAK-49313

-- START SAK-52495
ALTER TABLE GB_GRADABLE_OBJECT_T ADD LINEITEM_METADATA CLOB;
-- END SAK-52495
