-- SAK-43881 START
alter table MFR_TOPIC_T add SEND_TO_CALENDAR NUMBER(1,0) null;
alter table MFR_TOPIC_T add CALENDAR_BEGIN_ID VARCHAR2(255) null;
alter table MFR_TOPIC_T add CALENDAR_END_ID VARCHAR2(255) null;
alter table MFR_OPEN_FORUM_T add SEND_TO_CALENDAR NUMBER(1,0) null;
alter table MFR_OPEN_FORUM_T add CALENDAR_BEGIN_ID VARCHAR2(255) null;
alter table MFR_OPEN_FORUM_T add CALENDAR_END_ID VARCHAR2(255) null;
-- SAK-43881 END

