-- clear unchanged bundle properties
DELETE from SAKAI_MESSAGE_BUNDLE where PROP_VALUE is NULL;

-- this constraint may have been missed, it is ok if this line fails just comment it out
ALTER TABLE CONTENTREVIEW_ITEM ADD CONSTRAINT UK_8dngr1v68kkv4u11c1nvrjj1l UNIQUE (PROVIDERID, CONTENTID);

-- SAK-30079
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY AUTO_FORWARD NUMBER(10, 0);

-- SAK-43826 : Rubrics: Support weighted criterions

ALTER TABLE rbc_rubric ADD weighted NUMBER(1, 0) DEFAULT 0 NOT NULL;
ALTER TABLE rbc_criterion ADD weight FLOAT DEFAULT 0;

-- SAK-44637 - Make the Lessons Placement checkbox work
-- Note that SAK-44636 already added the column in sakai_20_1-20_2_mysql_conversion.sql
-- It is included here and commented out in case you need it.
ALTER TABLE lti_tools ADD pl_lessonsselection NUMBER(1, 0) DEFAULT 0;
-- Existing records needed to be switched on right before the feature is used
UPDATE lti_tools SET pl_lessonsselection = 1;
-- END SAK-44637

-- SAK-44810 - Add $Resource.id.history
-- This needs to rename a column in the DB because of a bug that keeps "settings"
-- from working as needed for this feature.
ALTER TABLE lti_tools RENAME COLUMN allowsettings TO allowsettings_ext;
-- If autoDDL somehow already ran and created allowsettings_ext - then you need
-- to copy data from the old column and delete it
-- UPDATE lti_tools SET allowsettings_ext=allowsettings;
-- ALTER TABLE lti_tools DROP COLUMN allowsettings;
-- END SAK-44810 

-- SAK-45174 Rubrics metadata datetime conversion
ALTER TABLE rbc_criterion DROP COLUMN created;
ALTER TABLE rbc_criterion DROP COLUMN modified;
ALTER TABLE rbc_evaluation DROP COLUMN created;
ALTER TABLE rbc_evaluation DROP COLUMN modified;
ALTER TABLE rbc_rating DROP COLUMN created;
ALTER TABLE rbc_rating DROP COLUMN modified;
ALTER TABLE rbc_rubric DROP COLUMN created;
ALTER TABLE rbc_rubric DROP COLUMN modified;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN created;
ALTER TABLE rbc_tool_item_rbc_assoc DROP COLUMN modified;

ALTER TABLE rbc_criterion ADD created TIMESTAMP NULL;
ALTER TABLE rbc_criterion ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_evaluation ADD created TIMESTAMP NULL;
ALTER TABLE rbc_evaluation ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_rating ADD created TIMESTAMP NULL;
ALTER TABLE rbc_rating ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_rubric ADD created TIMESTAMP NULL;
ALTER TABLE rbc_rubric ADD modified TIMESTAMP NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD created TIMESTAMP NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD modified TIMESTAMP NULL;

UPDATE rbc_criterion SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_criterion SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_evaluation SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_evaluation SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_rating SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_rating SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_rubric SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_rubric SET modified = current_timestamp WHERE modified IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET created = current_timestamp WHERE created IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET modified = current_timestamp WHERE modified IS NULL;
-- END SAK-45174

-- SAK-44019
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_ID NUMBER(10, 0);
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_LAUNCH_NEW_WINDOW NUMBER(1, 0);
-- END SAK-44019

-- SAK-41502
ALTER TABLE GB_GRADING_EVENT_T ADD IS_EXCLUDED NUMBER(10, 0);
-- END SAK-41502

-- SAK-45184
CREATE TABLE FILE_CONVERSION_QUEUE (
    ID                   NUMBER(19,0) NOT NULL,
    ATTEMPTS             NUMBER(10,0) NOT NULL,
    LAST_ATTEMPT_STARTED TIMESTAMP,
    REFERENCE            VARCHAR2(255 CHAR) NOT NULL,
    STATUS               VARCHAR2(16 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_FCI_REF_TYPE ON FILE_CONVERSION_QUEUE (REFERENCE);

create table MFR_DRAFT_RECIPIENT_T (
    ID           NUMBER(19,0) NOT NULL,
    BCC          NUMBER(1,0) DEFAULT 0 NOT NULL,
    DRAFT_ID     NUMBER(19,0) NOT NULL,
    RECIPIENT_ID VARCHAR2(255 CHAR) NOT NULL,
    TYPE         NUMBER(10,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE MFR_DRAFT_RECIPIENT_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;

CREATE INDEX MFR_DRAFT_REC_MSG_ID_I ON MFR_DRAFT_RECIPIENT_T (DRAFT_ID);

create table TASKS (
    ID          NUMBER(19,0) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR) NOT NULL,
    DUE         TIMESTAMP,
    REFERENCE   VARCHAR2(255 CHAR) NOT NULL,
    SITE_ID     VARCHAR2(99 CHAR),
    STARTS      TIMESTAMP,
    SYSTEM      NUMBER(1,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE TASKS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;

CREATE INDEX IDX_TASKS_REF_TYPE ON TASKS (REFERENCE);

create table USER_TASKS (
    ID           NUMBER(19,0) NOT NULL,
    COMPLETE     NUMBER(1,0),
    NOTES        CLOB,
    PRIORITY     NUMBER(10,0) NOT NULL,
    SOFT_DELETED NUMBER(1,0),
    USER_ID      VARCHAR2(99 CHAR) NOT NULL,
    TASK_ID      NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FKMJ3LSH7WX4O7S7I6HY80TBPSN FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);

CREATE SEQUENCE USER_TASKS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;

CREATE INDEX IDX_USER_TASK ON USER_TASKS (USER_ID, TASK_ID);

ALTER TABLE rbc_tool_item_rbc_assoc ADD active NUMBER(1,0) DEFAULT 1 NOT NULL;

ALTER TABLE rbc_tool_item_rbc_assoc DROP CONSTRAINT UKQ4BTC0DFYMI80BB5MP3VP3R7U;

CREATE INDEX FK1yhjvx9pxp5e76ijo0s6ahvsa ON rbc_tool_item_rbc_assoc(rubric_id);

DROP INDEX contentreview_provider_id_idx;

CREATE INDEX contentreview_provider_id_idx ON CONTENTREVIEW_ITEM(EXTERNALID);

-- LTI
ALTER TABLE lti_content ADD DESCRIPTION CLOB;
ALTER TABLE lti_content ADD protect NUMBER(1,0) DEFAULT 0;
ALTER TABLE lti_content DROP COLUMN sha256;
ALTER TABLE lti_tools ADD pl_privacy NUMBER(1, 0) DEFAULT 0;
ALTER TABLE lti_tools ADD pl_coursenav NUMBER(1, 0) DEFAULT 0;
ALTER TABLE lti_tools ADD lti13_auto_token VARCHAR2(1024 CHAR);
ALTER TABLE lti_tools ADD lti13_auto_state NUMBER(38,0);
ALTER TABLE lti_tools ADD lti13_auto_registration CLOB;

ALTER TABLE lti_tools RENAME COLUMN lti13_tool_keyset TO lti13_tool_keyset_old;
ALTER TABLE lti_tools ADD lti13_tool_keyset VARCHAR2(1024 CHAR);
UPDATE lti_tools SET lti13_tool_keyset = TO_CHAR(lti13_tool_keyset_old);
ALTER TABLE lti_tools DROP COLUMN lti13_tool_keyset_old;

ALTER TABLE lti_tools DROP COLUMN lti13_tool_kid;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_private;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_public;
ALTER TABLE lti_tools DROP COLUMN sha256;


ALTER TABLE SAKAI_PERSON_T RENAME COLUMN PHONETIC_PRONUNCIATION TO PHONETIC_OLD;
ALTER TABLE SAKAI_PERSON_T ADD PHONETIC_PRONUNCIATION VARCHAR2(255 CHAR);
UPDATE SAKAI_PERSON_T SET PHONETIC_PRONUNCIATION = TO_CHAR(PHONETIC_OLD);
ALTER TABLE SAKAI_PERSON_T DROP COLUMN PHONETIC_OLD;


ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY AUTO_FORWARD NUMBER(10,0);
DROP INDEX MFR_UNREAD_STATUS_I1;
CREATE INDEX MFR_UNREAD_STATUS_I1 ON MFR_UNREAD_STATUS_T(TOPIC_C);


-- Polls
ALTER TABLE POLL_OPTION MODIFY DELETED NUMBER(1, 0) DEFAULT 0 NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_ORDER NUMBER(10, 0) NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_POLL_ID NUMBER(19,0) NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_UUID VARCHAR2(255 CHAR) NOT NULL;

ALTER TABLE POLL_POLL MODIFY POLL_CREATION_DATE TIMESTAMP NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_DISPLAY_RESULT VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_IS_PUBLIC NUMBER(1, 0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_LIMIT_VOTE NUMBER(1, 0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_MAX_OPTIONS NUMBER(10,0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_MIN_OPTIONS NUMBER(10,0) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_OWNER VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_SITE_ID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_UUID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_CLOSE TIMESTAMP NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_OPEN TIMESTAMP NOT NULL;

ALTER TABLE POLL_VOTE MODIFY VOTE_DATE TIMESTAMP NOT NULL;
ALTER TABLE POLL_VOTE MODIFY VOTE_IP VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_VOTE MODIFY VOTE_POLL_ID NUMBER(19,0) NOT NULL;
ALTER TABLE POLL_VOTE MODIFY VOTE_SUBMISSION_ID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE POLL_VOTE MODIFY USER_ID VARCHAR2(255 CHAR) NOT NULL;


-- Site Setup Questions
ALTER TABLE SSQ_ANSWER MODIFY ANSWER VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE SSQ_ANSWER MODIFY FILL_IN_BLANK NUMBER(1,0) NOT NULL;
ALTER TABLE SSQ_ANSWER MODIFY ORDER_NUM NUMBER(10,0) NOT NULL;

ALTER TABLE SSQ_QUESTION MODIFY IS_CURRENT VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE SSQ_QUESTION MODIFY MULTIPLE_ANSWERS NUMBER(1,0) NOT NULL;
ALTER TABLE SSQ_QUESTION MODIFY ORDER_NUM NUMBER(10,0) NOT NULL;
ALTER TABLE SSQ_QUESTION MODIFY REQUIRED NUMBER(1,0) NOT NULL;

ALTER TABLE SSQ_USER_ANSWER MODIFY SITE_ID VARCHAR2(255 CHAR) NOT NULL;
ALTER TABLE SSQ_USER_ANSWER MODIFY USER_ID VARCHAR2(255 CHAR) NOT NULL;

ALTER TABLE SSQ_SITETYPE_QUESTIONS MODIFY SITE_TYPE VARCHAR2(255 CHAR) NOT NULL;

-- END SAK-45184

-- START SAK-42371
ALTER TABLE rbc_evaluation ADD status NUMBER(10,0) NOT NULL;
UPDATE rbc_evaluation SET status = 2;
-- END SAK-42371

CREATE SEQUENCE BULLHORN_ALERTS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
