
-- SAK-49540 START
ALTER TABLE lti_tools ADD pl_contextlaunch NUMBER(3) DEFAULT 0 NULL;
-- SAK-49540 END


-- SAK-48083 START
CREATE TABLE PUSH_SUBSCRIPTIONS (ID NUMBER(19) NOT NULL, AUTH VARCHAR2(255 CHAR) NOT NULL, CREATED timestamp NOT NULL, ENDPOINT VARCHAR2(2048 CHAR) NOT NULL, FINGERPRINT VARCHAR2(255 CHAR) NOT NULL, USER_ID VARCHAR2(99 CHAR) NOT NULL, USER_KEY VARCHAR2(255 CHAR) NOT NULL, CONSTRAINT PK_PUSH_SUBSCRIPTIONS PRIMARY KEY (ID), UNIQUE (FINGERPRINT));

CREATE SEQUENCE PUSH_SUBSCRIPTIONS_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER PUSH_SUBSCRIPTIONS_seq_tr
 BEFORE INSERT ON PUSH_SUBSCRIPTIONS FOR EACH ROW
 WHEN (NEW.ID IS NULL)
BEGIN
 SELECT PUSH_SUBSCRIPTIONS_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

CREATE INDEX IDX_PUSH_SUBSCRIPTIONS_USER ON PUSH_SUBSCRIPTIONS(USER_ID);
-- SAK-48083 END

-- SAK-49263 START
ALTER TABLE CONV_COMMENTS ADD CONSTRAINT FK5ivsmxyitqpbm7pmdnu3lnmyi FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_COMMENTS ADD CONSTRAINT FKfv490c54ofgxfq217hit2c048 FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_USER_STATISTICS ADD CONSTRAINT FKi9pfkqq0396p0kl718e9mrakk FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_POST_REACTION_TOTALS ADD CONSTRAINT FKirwlickqy5sf8o9ejk1qkuit6 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_POST_STATUS ADD CONSTRAINT FKlmu267g3wqev86qvu02nbt6el FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_TOPIC_STATUS ADD CONSTRAINT FKostfgg3nwdnlrtwy32ikdqpkg FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_TOPIC_REACTIONS ADD CONSTRAINT FKpwv7vrkag66g9kq6gghtc4uy1 FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_POSTS ADD CONSTRAINT FKqaspmpv6ull7whideia5i2cnb FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_TOPIC_REACTION_TOTALS ADD CONSTRAINT FKqu7eyh63vtkowyqoqa9xy7wmq FOREIGN KEY (TOPIC_ID) REFERENCES CONV_TOPICS (TOPIC_ID);
ALTER TABLE CONV_POST_REACTIONS ADD CONSTRAINT FKqv38yghf2km7vq1i717xywih6 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_POST_STATUS ADD CONSTRAINT FKrkf8re1yitfchr6weplt96h39 FOREIGN KEY (POST_ID) REFERENCES CONV_POSTS (POST_ID);
ALTER TABLE CONV_TOPIC_STATUS DROP COLUMN SITE_ID;
ALTER TABLE CONV_COMMENTS MODIFY POST_ID VARCHAR(36) NULL;
ALTER TABLE CONV_COMMENTS ALTER POST_ID SET DEFAULT null;
ALTER TABLE CONV_POST_REACTIONS MODIFY POST_ID VARCHAR(36) NULL;
ALTER TABLE CONV_POST_REACTIONS ALTER POST_ID SET DEFAULT null;
ALTER TABLE CONV_POST_STATUS MODIFY POST_ID VARCHAR(36) NULL;
ALTER TABLE CONV_POST_STATUS ALTER POST_ID SET DEFAULT null;
ALTER TABLE CONV_COMMENTS MODIFY TOPIC_ID VARCHAR(36) NULL;
ALTER TABLE CONV_COMMENTS ALTER TOPIC_ID SET DEFAULT null;
ALTER TABLE CONV_POSTS MODIFY TOPIC_ID VARCHAR(36) NULL;
ALTER TABLE CONV_POSTS ALTER TOPIC_ID SET DEFAULT null;
ALTER TABLE CONV_POST_STATUS MODIFY TOPIC_ID VARCHAR(36) NULL;
ALTER TABLE CONV_POST_STATUS ALTER TOPIC_ID SET DEFAULT null;
ALTER TABLE CONV_TOPIC_REACTIONS MODIFY TOPIC_ID VARCHAR(36) NULL;
ALTER TABLE CONV_TOPIC_REACTIONS ALTER TOPIC_ID SET DEFAULT null;
ALTER TABLE CONV_TOPIC_REACTION_TOTALS MODIFY TOPIC_ID VARCHAR(36) NULL;
ALTER TABLE CONV_TOPIC_REACTION_TOTALS ALTER TOPIC_ID SET DEFAULT null;
ALTER TABLE CONV_TOPIC_STATUS MODIFY TOPIC_ID VARCHAR(36) NULL;
ALTER TABLE CONV_TOPIC_STATUS ALTER TOPIC_ID SET DEFAULT null;
-- SAK-49263 END

