-- This script is to be run after running the sakai_23_3-23_4 script

-- clear unchanged bundle properties
DELETE FROM SAKAI_MESSAGE_BUNDLE where PROP_VALUE is NULL;

-- SAK-48106
UPDATE user_audits_log AS audits INNER JOIN SAKAI_USER_ID_MAP AS idmap ON audits.user_id = idmap.eid SET audits.user_id = idmap.user_id;
UPDATE user_audits_log AS audits INNER JOIN SAKAI_USER_ID_MAP AS idmap ON audits.action_user_id = idmap.eid SET audits.action_user_id = idmap.user_id;
-- END SAK-48106

-- SAK-48238
ALTER TABLE CONTENT_RESOURCE_BB_DELETE
    ADD RESOURCE_SHA256 VARCHAR(64) NULL;

ALTER TABLE CONTENT_RESOURCE_BODY_BINARY
    ADD RESOURCE_SHA256 VARCHAR(64) NULL;

ALTER TABLE CONTENT_RESOURCE
    ADD RESOURCE_SHA256 VARCHAR(64) NULL;

ALTER TABLE CONTENT_RESOURCE_DELETE
    ADD RESOURCE_SHA256 VARCHAR(64) NULL;

CREATE INDEX CONTENT_RESOURCE_BB_DEL_INDEX_SHA256 ON CONTENT_RESOURCE_BB_DELETE (RESOURCE_SHA256);
CREATE INDEX CONTENT_RESOURCE_BB_SHA256 ON CONTENT_RESOURCE_BODY_BINARY (RESOURCE_SHA256);
CREATE INDEX CONTENT_RESOURCE_FILE_PATH ON CONTENT_RESOURCE (FILE_PATH);
CREATE INDEX CONTENT_RESOURCE_FILE_PATH_DELETE_I ON CONTENT_RESOURCE_DELETE (FILE_PATH);
CREATE INDEX CONTENT_RESOURCE_SHA256 ON CONTENT_RESOURCE (RESOURCE_SHA256);
CREATE INDEX CONTENT_RESOURCE_SHA256_DELETE_I ON CONTENT_RESOURCE_DELETE (RESOURCE_SHA256);
-- END SAK-48238

-- S2U-12 --
ALTER TABLE SAM_ITEMFEEDBACK_T MODIFY TEXT LONGTEXT;
ALTER TABLE SAM_PUBLISHEDITEMFEEDBACK_T MODIFY TEXT LONGTEXT;
-- END S2U-12 --

-- S2U-42 --
CREATE TABLE CARDGAME_STAT_ITEM
(
    ID                VARCHAR(36)  NOT NULL,
    HITS              INT          NOT NULL,
    MARKED_AS_LEARNED BIT          NOT NULL,
    MISSES            INT          NOT NULL,
    PLAYER_ID         VARCHAR(255) NOT NULL,
    USER_ID           VARCHAR(255) NOT NULL,
    CONSTRAINT PK_CARDGAME_STAT_ITEM PRIMARY KEY (ID)
);

CREATE INDEX IDX_CARDGAME_STAT_ITEM_PLAYER_ID ON CARDGAME_STAT_ITEM (PLAYER_ID);
-- END S2U-42 --

-- S2U-27 --
ALTER TABLE MFR_OPEN_FORUM_T
    ADD IS_FAQ_FORUM BIT DEFAULT b'0' NOT NULL;
ALTER TABLE MFR_TOPIC_T
    ADD IS_FAQ_TOPIC BIT DEFAULT b'0' NOT NULL;
-- END S2U-27 --

-- S2U-34 --
-- IMPORTANT: This index must be deleted and may have a different name, maybe UK_dn0jue890jn9p7vs6tvnsf2gf or similar
-- Note: IF EXISTS syntax may not work in all MySQL versions, handle errors appropriately
DROP INDEX UKdn0jue890jn9p7vs6tvnsf2gf ON rbc_evaluation;
ALTER TABLE rbc_evaluation
    ADD CONSTRAINT UKqsk75a24pi108jpybtt16hshv UNIQUE (association_id, evaluated_item_id, evaluated_item_owner_id);

UPDATE rbc_evaluation SET evaluated_item_owner_id = RIGHT (evaluated_item_owner_id, 36) WHERE evaluated_item_owner_id like '/site/%';
ALTER TABLE rbc_tool_item_rbc_assoc_conf MODIFY parameters INT;
ALTER TABLE rbc_tool_item_rbc_assoc_conf ALTER parameters SET DEFAULT NULL;
-- END S2U-34 --

-- S2U-11 --
ALTER TABLE SAM_ITEMTEXT_T ADD ADDEDBUTNOTEXTRACTED BIT DEFAULT b'0' NOT NULL;
ALTER TABLE SAM_PUBLISHEDITEMTEXT_T ADD ADDEDBUTNOTEXTRACTED BIT DEFAULT b'0' NOT NULL;
-- END S2U-11 --

-- S2U-39 --
CREATE TABLE rwikipagegroups
(
    rwikiobjectid VARCHAR(36) NOT NULL,
    groupid       VARCHAR(255) NULL
);
-- END S2U-39 --

-- S2U-23 --
ALTER TABLE SAM_ASSESSFEEDBACK_T ADD SHOWCORRECTION BIT DEFAULT b'0' NOT NULL;
ALTER TABLE SAM_PUBLISHEDFEEDBACK_T ADD SHOWCORRECTION BIT DEFAULT b'0' NOT NULL;
-- to preserve the complete functionality on assessments previous to the patch with 'showcorrectresponse' enabled
UPDATE SAM_PUBLISHEDFEEDBACK_T SET showcorrection = 1 WHERE showcorrection = 0 AND showcorrectresponse = 1;
UPDATE SAM_ASSESSFEEDBACK_T SET showcorrection = 1 WHERE showcorrection = 0 AND showcorrectresponse = 1;
-- END S2U-23 --

-- S2U-29 --
ALTER TABLE MFR_PVT_MSG_USR_T ADD READ_RECEIPT BIT NULL;
-- END S2U-29 --

-- SAK-49591 --
CREATE TABLE SAM_ITEMHISTORICAL_T
(
    ITEMHISTORICALID BIGINT AUTO_INCREMENT NOT NULL,
    ITEMID           BIGINT       NOT NULL,
    MODIFIEDBY       VARCHAR(255) NOT NULL,
    MODIFIEDDATE     datetime(6)     NOT NULL,
    CONSTRAINT PK_SAM_ITEMHISTORICAL_T PRIMARY KEY (ITEMHISTORICALID)
);

CREATE INDEX SAM_ITEMHISTORICAL_ITEMID_I ON SAM_ITEMHISTORICAL_T(ITEMID);

ALTER TABLE SAM_ITEMHISTORICAL_T
    ADD CONSTRAINT FKioim26rixhda4r42nrlqysh3w FOREIGN KEY (ITEMID) REFERENCES SAM_ITEM_T (ITEMID);
-- END SAK-49591 --



-- S2U-32 and S2U-28 --
CREATE TABLE tagservice_tagassociation
(
    id      VARCHAR(99) NOT NULL,
    item_id VARCHAR(255) NULL,
    tag_id  VARCHAR(255) NULL,
    CONSTRAINT PK_TAGSERVICE_TAGASSOCIATION PRIMARY KEY (id)
);

ALTER TABLE tagservice_tagassociation ADD CONSTRAINT UK7tc7vcvcb0bw8moqdu3giik6o UNIQUE (tag_id, item_id);

-- Permission added in 12 might not be present
INSERT IGNORE INTO SAKAI_REALM_FUNCTION (function_name) VALUES ('tagservice.manage');

-- Add this for every role able to create and manage tags on a site, you'll need to add the tool too
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'tagservice.manage'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'tagservice.manage'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'tagservice.manage'));

-- Add this to populate existing sites with the permission
START TRANSACTION;
CREATE TEMPORARY TABLE PERMISSIONS_SRC_TEMP (ROLE_NAME VARCHAR(99), FUNCTION_NAME VARCHAR(99));
CREATE TEMPORARY TABLE PERMISSIONS_TEMP (ROLE_KEY INTEGER, FUNCTION_KEY INTEGER);

INSERT INTO PERMISSIONS_SRC_TEMP values ('maintain','tagservice.manage');
INSERT INTO PERMISSIONS_SRC_TEMP values ('Instructor','tagservice.manage');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES ('Teaching Assistant','tagservice.manage');

INSERT INTO PERMISSIONS_TEMP (ROLE_KEY, FUNCTION_KEY)
  SELECT SRR.ROLE_KEY, SRF.FUNCTION_KEY
    from PERMISSIONS_SRC_TEMP TMPSRC
    JOIN SAKAI_REALM_ROLE SRR ON (TMPSRC.ROLE_NAME = SRR.ROLE_NAME)
    JOIN SAKAI_REALM_FUNCTION SRF ON (TMPSRC.FUNCTION_NAME = SRF.FUNCTION_NAME);

INSERT INTO SAKAI_REALM_RL_FN (REALM_KEY, ROLE_KEY, FUNCTION_KEY)
  SELECT SRRFD.REALM_KEY, SRRFD.ROLE_KEY, TMP.FUNCTION_KEY
  FROM
    (SELECT DISTINCT SRRF.REALM_KEY, SRRF.ROLE_KEY FROM SAKAI_REALM_RL_FN SRRF) SRRFD
    JOIN PERMISSIONS_TEMP TMP ON (SRRFD.ROLE_KEY = TMP.ROLE_KEY)
    JOIN SAKAI_REALM SR ON (SRRFD.REALM_KEY = SR.REALM_KEY)
    WHERE SR.REALM_ID != '!site.helper' AND SR.REALM_ID NOT LIKE '!user.template%'
    AND NOT EXISTS (
        SELECT 1
            FROM SAKAI_REALM_RL_FN SRRFI
            WHERE SRRFI.REALM_KEY=SRRFD.REALM_KEY AND SRRFI.ROLE_KEY=SRRFD.ROLE_KEY AND SRRFI.FUNCTION_KEY=TMP.FUNCTION_KEY
    );
DROP TABLE PERMISSIONS_SRC_TEMP;
DROP TABLE PERMISSIONS_TEMP;
COMMIT;
-- END S2U-32 and S2U-28 --

-- S2U-21 --
CREATE TABLE SAM_SEBVALIDATION_T
(
    ID                    BIGINT AUTO_INCREMENT NOT NULL,
    PUBLISHEDASSESSMENTID BIGINT        NOT NULL,
    AGENTID               VARCHAR(99)   NOT NULL,
    URL                   VARCHAR(1000) NOT NULL,
    CONFIGKEYHASH         VARCHAR(64) NULL,
    EXAMKEYHASH           VARCHAR(64) NULL,
    EXPIRED               BIT           NOT NULL,
    CONSTRAINT PK_SAM_SEBVALIDATION_T PRIMARY KEY (ID)
);

CREATE INDEX SAM_SEB_INDEX ON SAM_SEBVALIDATION_T(PUBLISHEDASSESSMENTID, AGENTID);
-- END S2U-21 --

-- S2U-14 --
ALTER TABLE SAM_PUBLISHEDITEM_T ADD CANCELLATION INT DEFAULT 0 NOT NULL;
-- END S2U-14 --

-- S2U-5 --
ALTER TABLE rbc_rubric ADD adhoc BIT NULL;
-- End S2U-5 --

-- S2U-35 --
CREATE TABLE COND_CONDITION
(
    ID        VARCHAR(36)  NOT NULL,
    ARGUMENT  VARCHAR(999) NULL,
    ITEM_ID   VARCHAR(99) NULL,
    OPERATOR  VARCHAR(99) NULL,
    SITE_ID   VARCHAR(36) NOT NULL,
    TOOL_ID   VARCHAR(99) NOT NULL,
    COND_TYPE VARCHAR(99) NOT NULL,
    CONSTRAINT PK_COND_CONDITION PRIMARY KEY (ID)
);

CREATE TABLE COND_PARENT_CHILD
(
    PARENT_ID VARCHAR(36) NOT NULL,
    CHILD_ID  VARCHAR(36) NOT NULL,
    CONSTRAINT PK_COND_PARENT_CHILD PRIMARY KEY (PARENT_ID, CHILD_ID)
);

CREATE INDEX FKiudewpg6wux68j19ropff9wv3 ON COND_PARENT_CHILD(CHILD_ID);
CREATE INDEX IDX_CONDITION_SITE_ID ON COND_CONDITION(SITE_ID);
ALTER TABLE COND_PARENT_CHILD ADD CONSTRAINT FKiudewpg6wux68j19ropff9wv3 FOREIGN KEY (CHILD_ID) REFERENCES COND_CONDITION (ID);
ALTER TABLE COND_PARENT_CHILD ADD CONSTRAINT FKmb0yfgpop85k1b7liyogall6u FOREIGN KEY (PARENT_ID) REFERENCES COND_CONDITION (ID);

-- Permission added might not be present
INSERT IGNORE INTO SAKAI_REALM_FUNCTION (FUNCTION_NAME) VALUES ('conditions.update.condition');

-- Add this for every role able to create and manage conditions on a site, you'll need to add the tool too
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'conditions.update.condition'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'conditions.update.condition'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'conditions.update.condition'));

-- Add this to populate existing sites with the permission
START TRANSACTION;
CREATE TEMPORARY TABLE PERMISSIONS_SRC_TEMP (ROLE_NAME VARCHAR(99), FUNCTION_NAME VARCHAR(99));
CREATE TEMPORARY TABLE PERMISSIONS_TEMP (ROLE_KEY INTEGER, FUNCTION_KEY INTEGER);

INSERT INTO PERMISSIONS_SRC_TEMP values ('maintain','conditions.update.condition');
INSERT INTO PERMISSIONS_SRC_TEMP values ('Instructor','conditions.update.condition');
INSERT INTO PERMISSIONS_SRC_TEMP VALUES ('Teaching Assistant','conditions.update.condition');

INSERT INTO PERMISSIONS_TEMP (ROLE_KEY, FUNCTION_KEY)
  SELECT SRR.ROLE_KEY, SRF.FUNCTION_KEY
    from PERMISSIONS_SRC_TEMP TMPSRC
    JOIN SAKAI_REALM_ROLE SRR ON (TMPSRC.ROLE_NAME = SRR.ROLE_NAME)
    JOIN SAKAI_REALM_FUNCTION SRF ON (TMPSRC.FUNCTION_NAME = SRF.FUNCTION_NAME);

INSERT INTO SAKAI_REALM_RL_FN (REALM_KEY, ROLE_KEY, FUNCTION_KEY)
  SELECT SRRFD.REALM_KEY, SRRFD.ROLE_KEY, TMP.FUNCTION_KEY
  FROM
    (SELECT DISTINCT SRRF.REALM_KEY, SRRF.ROLE_KEY FROM SAKAI_REALM_RL_FN SRRF) SRRFD
    JOIN PERMISSIONS_TEMP TMP ON (SRRFD.ROLE_KEY = TMP.ROLE_KEY)
    JOIN SAKAI_REALM SR ON (SRRFD.REALM_KEY = SR.REALM_KEY)
    WHERE SR.REALM_ID != '!site.helper' AND SR.REALM_ID NOT LIKE '!user.template%'
    AND NOT EXISTS (
        SELECT 1
            FROM SAKAI_REALM_RL_FN SRRFI
            WHERE SRRFI.REALM_KEY=SRRFD.REALM_KEY AND SRRFI.ROLE_KEY=SRRFD.ROLE_KEY AND SRRFI.FUNCTION_KEY=TMP.FUNCTION_KEY
    );
DROP TABLE PERMISSIONS_SRC_TEMP;
DROP TABLE PERMISSIONS_TEMP;
COMMIT;
-- END S2U-35 --

-- S2U-46 --
CREATE TABLE mc_site_synchronization
(
    id                VARCHAR(99)  NOT NULL,
    creation_status   INT DEFAULT NULL,
    forced            BIT NULL,
    site_id           VARCHAR(99) NOT NULL,
    status            INT DEFAULT NULL,
    status_updated_at datetime(6) DEFAULT NULL,
    date_from         datetime(6) DEFAULT NULL,
    date_to           datetime(6) DEFAULT NULL,
    team_id           VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MC_SITE_SYNCHRONIZATION PRIMARY KEY (id)
);

ALTER TABLE mc_site_synchronization ADD CONSTRAINT UK6x6fys6nhedw6c6nsxsjeimso UNIQUE (site_id, team_id);

CREATE TABLE mc_group_synchronization
(
    id                VARCHAR(99)  NOT NULL,
    channel_id        VARCHAR(255) NOT NULL,
    group_id          VARCHAR(255) NOT NULL,
    status            INT         DEFAULT NULL,
    status_updated_at datetime(6) DEFAULT NULL,
    parentId          VARCHAR(99) NULL,
    CONSTRAINT PK_MC_GROUP_SYNCHRONIZATION PRIMARY KEY (id)
);

ALTER TABLE mc_group_synchronization ADD CONSTRAINT UKqnuqf1dw886mb7utou0fuguag UNIQUE (parentId, group_id, channel_id);
ALTER TABLE mc_group_synchronization ADD CONSTRAINT FKdagin8c7bia0gdrbp9hsoltap FOREIGN KEY (parentId) REFERENCES mc_site_synchronization (id) ON UPDATE RESTRICT ON DELETE CASCADE;

CREATE TABLE mc_config_item
(
    item_key VARCHAR(255) NOT NULL,
    value    VARCHAR(255) NULL,
    CONSTRAINT PK_MC_CONFIG_ITEM PRIMARY KEY (item_key)
);

CREATE TABLE mc_log
(
    id         BIGINT AUTO_INCREMENT NOT NULL,
    context    LONGTEXT NULL,
    event      VARCHAR(255) NULL,
    event_date datetime(6) DEFAULT NULL,
    status     INT      DEFAULT NULL,
    CONSTRAINT PK_MC_LOG PRIMARY KEY (id)
);
-- END S2U-46 --

-- S2U-47 --
CREATE TABLE meeting_providers
(
    provider_id   VARCHAR(99)  NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    CONSTRAINT PK_MEETING_PROVIDERS PRIMARY KEY (provider_id)
);

CREATE TABLE meetings
(
    meeting_id          VARCHAR(99)  NOT NULL,
    meeting_description LONGTEXT NULL,
    meeting_end_date    datetime(0) DEFAULT NULL,
    meeting_owner_id    VARCHAR(99) NULL,
    meeting_site_id     VARCHAR(99) NULL,
    meeting_start_date  datetime(0) DEFAULT NULL,
    meeting_title       VARCHAR(255) NOT NULL,
    meeting_url         VARCHAR(255) NULL,
    meeting_provider_id VARCHAR(99) NULL,
    CONSTRAINT PK_MEETINGS PRIMARY KEY (meeting_id)
);

CREATE INDEX FKll5xpyhfblhrv68ant5vjt58g ON meetings(meeting_provider_id);

ALTER TABLE meetings
    ADD CONSTRAINT FKll5xpyhfblhrv68ant5vjt58g FOREIGN KEY (meeting_provider_id) REFERENCES meeting_providers (provider_id);

CREATE TABLE meeting_properties
(
    prop_id         BIGINT AUTO_INCREMENT NOT NULL,
    prop_name       VARCHAR(255) NOT NULL,
    prop_value      VARCHAR(255) NULL,
    prop_meeting_id VARCHAR(99) NULL,
    CONSTRAINT PK_MEETING_PROPERTIES PRIMARY KEY (prop_id)
);

CREATE INDEX FKtnycb0vso79ex8271r5i7lfj7 ON meeting_properties(prop_meeting_id);

ALTER TABLE meeting_properties
    ADD CONSTRAINT FKtnycb0vso79ex8271r5i7lfj7 FOREIGN KEY (prop_meeting_id) REFERENCES meetings (meeting_id);

CREATE TABLE meeting_attendees
(
    attendee_id         BIGINT AUTO_INCREMENT NOT NULL,
    attendee_object_id  VARCHAR(255) NULL,
    attendee_type       INT DEFAULT NULL,
    attendee_meeting_id VARCHAR(99) NULL,
    CONSTRAINT PK_MEETING_ATTENDEES PRIMARY KEY (attendee_id)
);

CREATE INDEX FKb3w1vh9geqoc402nj497btf3v ON meeting_attendees(attendee_meeting_id);

ALTER TABLE meeting_attendees
    ADD CONSTRAINT FKb3w1vh9geqoc402nj497btf3v FOREIGN KEY (attendee_meeting_id) REFERENCES meetings (meeting_id);
-- END S2U-47 --

-- S2U-49 --
CREATE TABLE mc_access_token
(
    sakaiUserId     VARCHAR(255) NOT NULL,
    accessToken     LONGTEXT NULL,
    account         VARCHAR(255) NULL,
    microsoftUserId VARCHAR(255) NULL,
    CONSTRAINT PK_MC_ACCESS_TOKEN PRIMARY KEY (sakaiUserId)
);

DROP TABLE IF EXISTS ONEDRIVE_USER;
-- END S2U-49 --

-- S2U-16 --
ALTER TABLE SAM_ITEMGRADING_T ADD ATTEMPTDATE datetime(6) DEFAULT NULL;

CREATE TABLE SAM_SECTIONGRADING_T
(
    SECTIONGRADINGID    BIGINT AUTO_INCREMENT NOT NULL,
    ASSESSMENTGRADINGID BIGINT       NOT NULL,
    PUBLISHEDSECTIONID  BIGINT       NOT NULL,
    AGENTID             VARCHAR(255) NOT NULL,
    ATTEMPTDATE         datetime(6) DEFAULT NULL,
    CONSTRAINT PK_SAM_SECTIONGRADING_T PRIMARY KEY (SECTIONGRADINGID)
);

ALTER TABLE SAM_SECTIONGRADING_T
    ADD CONSTRAINT uniqueStudentSectionResponse UNIQUE (ASSESSMENTGRADINGID, PUBLISHEDSECTIONID, AGENTID);
-- S2U-16 --

-- S2U-19 --
ALTER TABLE SAM_ITEM_T ADD isFixed BIT DEFAULT b'0' NOT NULL;
ALTER TABLE SAM_PUBLISHEDITEM_T ADD isFixed BIT DEFAULT b'0' NOT NULL;
-- END S2U-19 --

-- SAK-46714 --
ALTER TABLE lti_tools DROP COLUMN lti13_platform_private;
ALTER TABLE lti_tools DROP COLUMN lti13_platform_private_next;
ALTER TABLE lti_tools DROP COLUMN lti13_platform_public;
ALTER TABLE lti_tools DROP COLUMN lti13_platform_public_next;
ALTER TABLE lti_tools DROP COLUMN lti13_platform_public_next_at;
ALTER TABLE lti_tools DROP COLUMN lti13_platform_public_old;
ALTER TABLE lti_tools DROP COLUMN lti13_platform_public_old_at;
-- END SAK-46714 --

-- SAK-50378 --
-- These are columns dropped by SAK-50378 but will not be dropped by 
-- the Sakai 25 conversion scripts until Sakai 25.2 or later
-- New Sakai 25 instances won't have these columns but the columns will
-- not be removed as systems go from Sakai 23 to Sakai 25.0 or 25.1 to allow
-- for forward and backward version movement for early versions of Sakai 25
-- They are included here to note than when the schema comparison
-- is done prior to the 25 release - these will show up but not be included
-- in the final 25.0 conversion script

-- ALTER TABLE lti_content DROP COLUMN pagetitle;
-- ALTER TABLE lti_content DROP COLUMN toolorder;
-- ALTER TABLE lti_content DROP COLUMN consumerkey;
-- ALTER TABLE lti_content DROP COLUMN secret;
-- ALTER TABLE lti_content DROP COLUMN settings_ext;
-- ALTER TABLE lti_content DROP COLUMN fa_icon;

-- ALTER TABLE lti_tools DROP COLUMN allowtitle;
-- ALTER TABLE lti_tools DROP COLUMN pagetitle;
-- ALTER TABLE lti_tools DROP COLUMN allowpagetitle;
-- ALTER TABLE lti_tools DROP COLUMN allowlaunch;
-- ALTER TABLE lti_tools DROP COLUMN allowframeheight;
-- ALTER TABLE lti_tools DROP COLUMN allowfa_icon;
-- ALTER TABLE lti_tools DROP COLUMN toolorder;
-- ALTER TABLE lti_tools DROP COLUMN allowsettings_ext;
-- ALTER TABLE lti_tools DROP COLUMN allowconsumerkey;
-- ALTER TABLE lti_tools DROP COLUMN allowsecret;
-- ALTER TABLE lti_tools DROP COLUMN lti11_launch_type;
-- END SAK-50378 --

-- SAK-50536
ALTER TABLE PROFILE_WALL_ITEM_COMMENTS_T DROP FOREIGN KEY FKeat6qfjdwwkkxj6aifinujajb;

DROP TABLE PROFILE_COMPANY_PROFILES_T;
DROP TABLE PROFILE_FRIENDS_T;
DROP TABLE PROFILE_GALLERY_IMAGES_T;
DROP TABLE PROFILE_KUDOS_T;
DROP TABLE PROFILE_MESSAGES_T;
DROP TABLE PROFILE_MESSAGE_PARTICIPANTS_T;
DROP TABLE PROFILE_MESSAGE_THREADS_T;
DROP TABLE PROFILE_PRIVACY_T;
DROP TABLE PROFILE_STATUS_T;
DROP TABLE PROFILE_WALL_ITEMS_T;
DROP TABLE PROFILE_WALL_ITEM_COMMENTS_T;

ALTER TABLE PROFILE_SOCIAL_INFO_T DROP COLUMN MYSPACE_URL;
ALTER TABLE PROFILE_SOCIAL_INFO_T DROP COLUMN SKYPE_USERNAME;
ALTER TABLE PROFILE_SOCIAL_INFO_T DROP COLUMN TWITTER_URL;

ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN EMAIL_CONFIRM;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN EMAIL_MESSAGE_NEW;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN EMAIL_MESSAGE_REPLY;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN EMAIL_REQUEST;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN EMAIL_WALL_ITEM_NEW;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN EMAIL_WORKSITE_NEW;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN SHOW_GALLERY_FEED;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN SHOW_KUDOS;
ALTER TABLE PROFILE_PREFERENCES_T DROP COLUMN SHOW_ONLINE_STATUS;
-- END SAK-50536

-- SAK-49953
ALTER TABLE PROFILE_EXTERNAL_INTEGRATION_T DROP COLUMN TWITTER_SECRET;
ALTER TABLE PROFILE_EXTERNAL_INTEGRATION_T DROP COLUMN TWITTER_TOKEN;
-- END SAK-49953

-- SAK-50200
CREATE TABLE SCORM_ACTIVITY_TREE_HOLDER_T
(
    HOLDER_ID          BIGINT AUTO_INCREMENT NOT NULL,
    CONTENT_PACKAGE_ID BIGINT   DEFAULT NULL,
    LEARNER_ID         VARCHAR(255) NULL,
    ACT_TREE           LONGBLOB DEFAULT NULL,
    CONSTRAINT PK_SCORM_ACTIVITY_TREE_HOLDER_T PRIMARY KEY (HOLDER_ID)
);

CREATE TABLE SCORM_ADL_VALID_REQUESTS_T
(
    VALID_REQUESTS_ID        BIGINT AUTO_INCREMENT NOT NULL,
    IS_START_ENABLED         BIT NULL,
    IS_RESUME_ALL_ENABLED    BIT NULL,
    IS_CONTINUE_ENABLED      BIT NULL,
    IS_CONTINUE_EXIT_ENABLED BIT NULL,
    IS_PREVIOUS_ENABLED      BIT NULL,
    IS_SUSPEND_VALID         BIT NULL,
    CONSTRAINT PK_SCORM_ADL_VALID_REQUESTS_T PRIMARY KEY (VALID_REQUESTS_ID)
);

CREATE TABLE SCORM_ATTEMPT_T
(
    ATTEMPT_ID         BIGINT AUTO_INCREMENT NOT NULL,
    CONTENT_PACKAGE_ID BIGINT DEFAULT NULL,
    COURSE_ID          VARCHAR(255) NULL,
    LEARNER_ID         VARCHAR(255) NULL,
    LEARNER_NAME       VARCHAR(255) NULL,
    ATTEMPT_NUMBER     BIGINT DEFAULT NULL,
    CREATED_ON         datetime(6) DEFAULT NULL,
    MODIFIED_ON        datetime(6) DEFAULT NULL,
    IS_SUSPENDED       BIT NULL,
    IS_NOT_EXITED      BIT NULL,
    CONSTRAINT PK_SCORM_ATTEMPT_T PRIMARY KEY (ATTEMPT_ID)
);

CREATE TABLE SCORM_CONTENT_PACKAGE_T
(
    PACKAGE_ID           BIGINT AUTO_INCREMENT NOT NULL,
    TITLE                VARCHAR(255) NULL,
    RESOURCE_ID          VARCHAR(255) NULL,
    MANIFEST_ID          TINYBLOB DEFAULT NULL,
    MANIFEST_RESOURCE_ID VARCHAR(255) NULL,
    CONTEXT              VARCHAR(255) NULL,
    URL                  VARCHAR(255) NULL,
    RELEASE_ON           datetime(6) DEFAULT NULL,
    DUE_ON               datetime(6) DEFAULT NULL,
    ACCEPT_UNTIL         datetime(6) DEFAULT NULL,
    CREATED_ON           datetime(6) DEFAULT NULL,
    CREATED_BY           VARCHAR(255) NULL,
    MODIFIED_ON          datetime(6) DEFAULT NULL,
    MODIFIED_BY          VARCHAR(255) NULL,
    NUMBER_OF_TRIES      INT      DEFAULT NULL,
    IS_DELETED           BIT NULL,
    SHOW_TOC             BIT NOT NULL,
    SHOW_NAV_BAR         BIT NOT NULL,
    CONSTRAINT PK_SCORM_CONTENT_PACKAGE_T PRIMARY KEY (PACKAGE_ID)
);

CREATE TABLE SCORM_CP_MANIFEST_T
(
    MANIFEST_ID        BIGINT AUTO_INCREMENT NOT NULL,
    ACT_TREE_PROTOTYPE LONGBLOB DEFAULT NULL,
    CONSTRAINT PK_SCORM_CP_MANIFEST_T PRIMARY KEY (MANIFEST_ID)
);

CREATE TABLE SCORM_DATAMANAGER_T
(
    DATAMANAGER_ID     BIGINT AUTO_INCREMENT NOT NULL,
    CONTENT_PACKAGE_ID BIGINT DEFAULT NULL,
    COURSE_ID          VARCHAR(255) NULL,
    SCO_ID             VARCHAR(255) NOT NULL,
    ACTIVITY_ID        VARCHAR(255) NULL,
    USER_ID            VARCHAR(255) NULL,
    TITLE              VARCHAR(255) NULL,
    ATTEMPT_NUMBER     BIGINT DEFAULT NULL,
    BEGIN_DATE         datetime(6) DEFAULT NULL,
    LAST_MODIFIED_DATE datetime(6) DEFAULT NULL,
    CONSTRAINT PK_SCORM_DATAMANAGER_T PRIMARY KEY (DATAMANAGER_ID)
);

CREATE TABLE SCORM_DATAMODEL_T
(
    DATAMODEL_ID    BIGINT AUTO_INCREMENT NOT NULL,
    CLASS_TYPE      VARCHAR(255) NOT NULL,
    BINDING         VARCHAR(255) NULL,
    NAV_REQUESTS    BIGINT DEFAULT NULL,
    CURRENT_REQUEST VARCHAR(255) NULL,
    LEARNER_ID      VARCHAR(255) NULL,
    SCO_ID          VARCHAR(255) NULL,
    PROTOCOL        VARCHAR(255) NULL,
    HOST            VARCHAR(255) NULL,
    PORT            INT    DEFAULT NULL,
    FILE_NAME       VARCHAR(255) NULL,
    AUTHORITY       VARCHAR(255) NULL,
    REF             VARCHAR(255) NULL,
    COURSE_ID       VARCHAR(255) NULL,
    ATTEMPT_NUMBER  VARCHAR(255) NULL,
    CONSTRAINT PK_SCORM_DATAMODEL_T PRIMARY KEY (DATAMODEL_ID)
);

CREATE TABLE SCORM_DELIMITER_T
(
    DELIM_ID      BIGINT AUTO_INCREMENT NOT NULL,
    DESC_NAME     VARCHAR(255) NULL,
    DEFAULT_VALUE VARCHAR(255) NULL,
    VALUE_SPM     INT    DEFAULT NULL,
    VALIDATOR     BIGINT DEFAULT NULL,
    VALUE         VARCHAR(255) NULL,
    CONSTRAINT PK_SCORM_DELIMITER_T PRIMARY KEY (DELIM_ID)
);

CREATE TABLE SCORM_DELIMIT_DESC_T
(
    DELIM_DESC_ID BIGINT AUTO_INCREMENT NOT NULL,
    DESC_NAME     VARCHAR(255) NULL,
    DEFAULT_VALUE VARCHAR(255) NULL,
    VALUE_SPM     INT    DEFAULT NULL,
    VALIDATOR     BIGINT DEFAULT NULL,
    CONSTRAINT PK_SCORM_DELIMIT_DESC_T PRIMARY KEY (DELIM_DESC_ID)
);

CREATE TABLE SCORM_ELEMENT_DESC_T
(
    ELEM_DESC_ID     BIGINT AUTO_INCREMENT NOT NULL,
    ED_BINDING       VARCHAR(255) NULL,
    IS_READABLE      BIT NULL,
    IS_WRITABLE      BIT NULL,
    INITIAL_VALUE    VARCHAR(255) NULL,
    IS_UNIQUE        BIT NULL,
    IS_WRITE_ONCE    BIT NULL,
    VALUE_SPM        INT DEFAULT NULL,
    SPM              INT DEFAULT NULL,
    OLD_SPM          INT DEFAULT NULL,
    IS_MAXIMUM       BIT NULL,
    IS_SHOW_CHILDREN BIT NULL,
    CONSTRAINT PK_SCORM_ELEMENT_DESC_T PRIMARY KEY (ELEM_DESC_ID)
);

CREATE TABLE SCORM_ELEMENT_T
(
    ELEMENT_ID     BIGINT AUTO_INCREMENT NOT NULL,
    CLASS_TYPE     VARCHAR(255) NOT NULL,
    `DESCRIPTION`  BIGINT DEFAULT NULL,
    PARENT         BIGINT DEFAULT NULL,
    VALUE          LONGTEXT NULL,
    IS_INITIALIZED BIT NULL,
    TRUNC_SPM      BIT NULL,
    ELEMENT_DM     BIGINT DEFAULT NULL,
    NAVIGATION_DM  BIGINT DEFAULT NULL,
    BINDING        VARCHAR(255) NULL,
    IS_RANDOMIZED  BIT NULL,
    DM_COUNT       INT    DEFAULT NULL,
    CONSTRAINT PK_SCORM_ELEMENT_T PRIMARY KEY (ELEMENT_ID)
);

CREATE TABLE SCORM_LAUNCH_DATA_T
(
    LAUNCH_DATA_ID         BIGINT AUTO_INCREMENT NOT NULL,
    ORG_IDENTIFIER         VARCHAR(255) NULL,
    ITEM_IDENTIFIER        VARCHAR(255) NULL,
    RESOURCE_IDENTIFIER    VARCHAR(255) NULL,
    MANIFEST_XML_BASE      VARCHAR(255) NULL,
    RESOURCES_XML_BASE     VARCHAR(255) NULL,
    RESOURCE_XML_BASE      VARCHAR(255) NULL,
    PARAMETERS             VARCHAR(255) NULL,
    PERSIST_STATE          VARCHAR(255) NULL,
    LOCATION               VARCHAR(255) NULL,
    SCORM_TYPE             VARCHAR(255) NULL,
    ITEM_TITLE             VARCHAR(255) NULL,
    DATA_FROM_LMS          VARCHAR(4000) NULL,
    TIME_LIMIT_ACTION      VARCHAR(255) NULL,
    MIN_NORMALIZED_MEASURE VARCHAR(255) NULL,
    ATTEMPT_ABS_DUR_LIMIT  VARCHAR(255) NULL,
    COMPLETION_THRESHOLD   VARCHAR(255) NULL,
    OBJECTIVES_LIST        VARCHAR(255) NULL,
    IS_PREVIOUS            BIT NULL,
    IS_CONTINUE            BIT NULL,
    IS_EXIT                BIT NULL,
    IS_EXIT_ALL            BIT NULL,
    IS_ABANDON             BIT NULL,
    IS_SUSPEND_ALL         BIT NULL,
    CONSTRAINT PK_SCORM_LAUNCH_DATA_T PRIMARY KEY (LAUNCH_DATA_ID)
);

CREATE TABLE SCORM_LIST_BINDINGS_T
(
    ELEMENT_ID BIGINT NOT NULL,
    SORT_ORDER INT    NOT NULL,
    BINDING    VARCHAR(255) NULL,
    CONSTRAINT PK_SCORM_LIST_BINDINGS_T PRIMARY KEY (ELEMENT_ID, SORT_ORDER)
);

CREATE TABLE SCORM_LIST_DELIMITERS_T
(
    ELEMENT_ID BIGINT NOT NULL,
    SORT_ORDER INT    NOT NULL,
    DELIM_ID   BIGINT NOT NULL,
    CONSTRAINT PK_SCORM_LIST_DELIMITERS_T PRIMARY KEY (ELEMENT_ID, SORT_ORDER)
);

CREATE TABLE SCORM_LIST_DELIM_DESC_T
(
    ELEM_DESC_ID  BIGINT NOT NULL,
    SORT_ORDER    INT    NOT NULL,
    DELIM_DESC_ID BIGINT NOT NULL,
    CONSTRAINT PK_SCORM_LIST_DELIM_DESC_T PRIMARY KEY (ELEM_DESC_ID, SORT_ORDER)
);

CREATE TABLE SCORM_LIST_ELEMENTS_T
(
    DATAMODEL_ID BIGINT NOT NULL,
    SORT_ORDER   INT    NOT NULL,
    ELEMENT_ID   BIGINT NOT NULL,
    CONSTRAINT PK_SCORM_LIST_ELEMENTS_T PRIMARY KEY (DATAMODEL_ID, SORT_ORDER)
);

CREATE TABLE SCORM_LIST_ELEM_DESC_T
(
    ELEM_DESC_ID BIGINT NOT NULL,
    SORT_ORDER   INT    NOT NULL,
    CHILD_ID     BIGINT NOT NULL,
    CONSTRAINT PK_SCORM_LIST_ELEM_DESC_T PRIMARY KEY (ELEM_DESC_ID, SORT_ORDER)
);

CREATE TABLE SCORM_LIST_LAUNCH_DATA_T
(
    MANIFEST_ID    BIGINT NOT NULL,
    SORT_ORDER     INT    NOT NULL,
    LAUNCH_DATA_ID BIGINT NOT NULL,
    CONSTRAINT PK_SCORM_LIST_LAUNCH_DATA_T PRIMARY KEY (MANIFEST_ID, SORT_ORDER)
);

CREATE TABLE SCORM_LIST_RECORDS_T
(
    ELEMENT_ID BIGINT NOT NULL,
    SORT_ORDER INT    NOT NULL,
    RECORD_ID  BIGINT NOT NULL,
    CONSTRAINT PK_SCORM_LIST_RECORDS_T PRIMARY KEY (ELEMENT_ID, SORT_ORDER)
);

CREATE TABLE SCORM_MAP_CHILDREN_T
(
    ELEMENT_ID    BIGINT       NOT NULL,
    CHILD_BINDING VARCHAR(255) NOT NULL,
    CHILD_ID      BIGINT       NOT NULL,
    CONSTRAINT PK_SCORM_MAP_CHILDREN_T PRIMARY KEY (ELEMENT_ID, CHILD_BINDING)
);

CREATE TABLE SCORM_MAP_DATAMODELS_T
(
    DATAMANAGER_ID BIGINT       NOT NULL,
    DM_BINDING     VARCHAR(255) NOT NULL,
    DATAMODEL_ID   BIGINT       NOT NULL,
    CONSTRAINT PK_SCORM_MAP_DATAMODELS_T PRIMARY KEY (DATAMANAGER_ID, DM_BINDING)
);

CREATE TABLE SCORM_MAP_ELEMENTS_T
(
    DATAMODEL_ID    BIGINT       NOT NULL,
    ELEMENT_BINDING VARCHAR(255) NOT NULL,
    ELEMENT_ID      BIGINT       NOT NULL,
    CONSTRAINT PK_SCORM_MAP_ELEMENTS_T PRIMARY KEY (DATAMODEL_ID, ELEMENT_BINDING)
);

CREATE TABLE SCORM_MAP_SCO_DATAMANAGER_T
(
    ATTEMPT_ID     BIGINT       NOT NULL,
    SCO_ID         VARCHAR(255) NOT NULL,
    DATAMANAGER_ID BIGINT DEFAULT NULL,
    CONSTRAINT PK_SCORM_MAP_SCO_DATAMANAGER_T PRIMARY KEY (ATTEMPT_ID, SCO_ID)
);

CREATE TABLE SCORM_TYPE_VALIDATOR_T
(
    ID                BIGINT AUTO_INCREMENT NOT NULL,
    VALIDATOR_TYPE    VARCHAR(255) NOT NULL,
    TYPE              VARCHAR(255) NULL,
    INCLUDE_SUB_SECS  BIT NULL,
    INTER_ALLOW_EMPTY BIT NULL,
    ELEMENT           VARCHAR(255) NULL,
    INTERACTION_TYPE  INT      DEFAULT NULL,
    INT_MAX           INT      DEFAULT NULL,
    INT_MIN           INT      DEFAULT NULL,
    LANG_ALLOW_EMPTY  BIT NULL,
    REAL_MAX DOUBLE DEFAULT NULL,
    REAL_MIN DOUBLE DEFAULT NULL,
    RESULT_VOCAB_LIST TINYBLOB DEFAULT NULL,
    SPM               INT      DEFAULT NULL,
    URI_SPM           INT      DEFAULT NULL,
    VOCAB_LIST        TINYBLOB DEFAULT NULL,
    CONSTRAINT PK_SCORM_TYPE_VALIDATOR_T PRIMARY KEY (ID)
);

CREATE TABLE SCORM_URL
(
    URL_ID    BIGINT AUTO_INCREMENT NOT NULL,
    PROTOCOL  VARCHAR(255) NULL,
    HOST      VARCHAR(255) NULL,
    PORT      INT DEFAULT NULL,
    FILE_NAME VARCHAR(255) NULL,
    AUTHORITY VARCHAR(255) NULL,
    REF       VARCHAR(255) NULL,
    CONSTRAINT PK_SCORM_URL PRIMARY KEY (URL_ID)
);

CREATE INDEX FK1iyus9lmmt8qxh9hqn9a79ag2 ON SCORM_LIST_ELEM_DESC_T (CHILD_ID);
CREATE INDEX FK4533ssr4ehx10yoxdbvht7o61 ON SCORM_MAP_CHILDREN_T (CHILD_ID);
CREATE INDEX FK60klo5ulb0o2fcxuwqvr4hrv6 ON SCORM_ELEMENT_T (ELEMENT_DM);
CREATE INDEX FKcnnvucotqnamlm25nth5km2oo ON SCORM_MAP_ELEMENTS_T (ELEMENT_ID);
CREATE INDEX FKg4d2lpi7xv1wigv3vigu62p1a ON SCORM_LIST_LAUNCH_DATA_T (LAUNCH_DATA_ID);
CREATE INDEX FKg4nnlyv9cv9c1i5n9g041eif5 ON SCORM_LIST_ELEMENTS_T (ELEMENT_ID);
CREATE INDEX FKh3hc0budun0he9373nrf3kpye ON SCORM_MAP_DATAMODELS_T (DATAMODEL_ID);
CREATE INDEX FKn7i3bcgfqnx8ugdtgu8oqcka6 ON SCORM_LIST_DELIMITERS_T (DELIM_ID);
CREATE INDEX FKneos81gsguh5rxddhly2fdor1 ON SCORM_ELEMENT_T (NAVIGATION_DM);
CREATE INDEX FKr5qj7hfctt9sqttk25g59j3pf ON SCORM_ELEMENT_T (`DESCRIPTION`);
CREATE INDEX FKrpg3ygmnj41wv762oycfeijfx ON SCORM_LIST_RECORDS_T (RECORD_ID);
CREATE INDEX FKt380u3n3bo4jfq7ugr1xovqqi ON SCORM_LIST_DELIM_DESC_T (DELIM_DESC_ID);
CREATE INDEX FKtmfmx4swa611msqjx864cldsn ON SCORM_ELEMENT_T (PARENT);
CREATE INDEX FK4yccihmov0qlo7uotini25hdp ON SCORM_DELIMITER_T(VALIDATOR);
CREATE INDEX FKg4mvbtnbxt32tkr9jv9j9ycbt ON SCORM_DELIMIT_DESC_T(VALIDATOR);
CREATE INDEX SCORM_DM_NAV_REQS_IDX ON SCORM_DATAMODEL_T (NAV_REQUESTS);

ALTER TABLE SCORM_LIST_ELEM_DESC_T
    ADD CONSTRAINT FK1iyus9lmmt8qxh9hqn9a79ag2 FOREIGN KEY (CHILD_ID) REFERENCES SCORM_ELEMENT_DESC_T (ELEM_DESC_ID);

ALTER TABLE SCORM_MAP_CHILDREN_T
    ADD CONSTRAINT FK4533ssr4ehx10yoxdbvht7o61 FOREIGN KEY (CHILD_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_DELIMITER_T
    ADD CONSTRAINT FK4yccihmov0qlo7uotini25hdp FOREIGN KEY (VALIDATOR) REFERENCES SCORM_TYPE_VALIDATOR_T (ID);

ALTER TABLE SCORM_ELEMENT_T
    ADD CONSTRAINT FK60klo5ulb0o2fcxuwqvr4hrv6 FOREIGN KEY (ELEMENT_DM) REFERENCES SCORM_DATAMODEL_T (DATAMODEL_ID);

ALTER TABLE SCORM_DATAMODEL_T
    ADD CONSTRAINT FK8hjtj5urddedfregxr65q8s2p FOREIGN KEY (NAV_REQUESTS) REFERENCES SCORM_ADL_VALID_REQUESTS_T (VALID_REQUESTS_ID);

ALTER TABLE SCORM_LIST_LAUNCH_DATA_T
    ADD CONSTRAINT FK9gqdu7cph1qg4ch6g4lwtl00b FOREIGN KEY (MANIFEST_ID) REFERENCES SCORM_CP_MANIFEST_T (MANIFEST_ID);

ALTER TABLE SCORM_MAP_ELEMENTS_T
    ADD CONSTRAINT FKcnnvucotqnamlm25nth5km2oo FOREIGN KEY (ELEMENT_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_MAP_ELEMENTS_T
    ADD CONSTRAINT FKdgxhepepwuaiw5uh4w6mtqae8 FOREIGN KEY (DATAMODEL_ID) REFERENCES SCORM_DATAMODEL_T (DATAMODEL_ID);

ALTER TABLE SCORM_LIST_LAUNCH_DATA_T
    ADD CONSTRAINT FKg4d2lpi7xv1wigv3vigu62p1a FOREIGN KEY (LAUNCH_DATA_ID) REFERENCES SCORM_LAUNCH_DATA_T (LAUNCH_DATA_ID);

ALTER TABLE SCORM_DELIMIT_DESC_T
    ADD CONSTRAINT FKg4mvbtnbxt32tkr9jv9j9ycbt FOREIGN KEY (VALIDATOR) REFERENCES SCORM_TYPE_VALIDATOR_T (ID);

ALTER TABLE SCORM_LIST_ELEMENTS_T
    ADD CONSTRAINT FKg4nnlyv9cv9c1i5n9g041eif5 FOREIGN KEY (ELEMENT_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_MAP_DATAMODELS_T
    ADD CONSTRAINT FKh3hc0budun0he9373nrf3kpye FOREIGN KEY (DATAMODEL_ID) REFERENCES SCORM_DATAMODEL_T (DATAMODEL_ID);

ALTER TABLE SCORM_LIST_ELEMENTS_T
    ADD CONSTRAINT FKh7wa55pxca3rfku4shfss0172 FOREIGN KEY (DATAMODEL_ID) REFERENCES SCORM_DATAMODEL_T (DATAMODEL_ID);

ALTER TABLE SCORM_LIST_RECORDS_T
    ADD CONSTRAINT FKiyfb34ngl98f4epoxeven69m4 FOREIGN KEY (ELEMENT_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_LIST_DELIMITERS_T
    ADD CONSTRAINT FKn7i3bcgfqnx8ugdtgu8oqcka6 FOREIGN KEY (DELIM_ID) REFERENCES SCORM_DELIMITER_T (DELIM_ID);

ALTER TABLE SCORM_ELEMENT_T
    ADD CONSTRAINT FKneos81gsguh5rxddhly2fdor1 FOREIGN KEY (NAVIGATION_DM) REFERENCES SCORM_DATAMODEL_T (DATAMODEL_ID);

ALTER TABLE SCORM_LIST_ELEM_DESC_T
    ADD CONSTRAINT FKo73u7xgfjlantpunhrx4nlwvi FOREIGN KEY (ELEM_DESC_ID) REFERENCES SCORM_ELEMENT_DESC_T (ELEM_DESC_ID);

ALTER TABLE SCORM_LIST_DELIMITERS_T
    ADD CONSTRAINT FKogldox6hqgvghusbp23oa27qc FOREIGN KEY (ELEMENT_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_LIST_DELIM_DESC_T
    ADD CONSTRAINT FKp1o8regkt7yiwhf8wp5ol35ea FOREIGN KEY (ELEM_DESC_ID) REFERENCES SCORM_ELEMENT_DESC_T (ELEM_DESC_ID);

ALTER TABLE SCORM_MAP_DATAMODELS_T
    ADD CONSTRAINT FKptcj0mys6w5gv3mcn5o3dvi47 FOREIGN KEY (DATAMANAGER_ID) REFERENCES SCORM_DATAMANAGER_T (DATAMANAGER_ID);

ALTER TABLE SCORM_MAP_CHILDREN_T
    ADD CONSTRAINT FKr4ulcoxk50jgi5p58o0vkj6yd FOREIGN KEY (ELEMENT_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_ELEMENT_T
    ADD CONSTRAINT FKr5qj7hfctt9sqttk25g59j3pf FOREIGN KEY (`DESCRIPTION`) REFERENCES SCORM_ELEMENT_DESC_T (ELEM_DESC_ID);

ALTER TABLE SCORM_LIST_RECORDS_T
    ADD CONSTRAINT FKrpg3ygmnj41wv762oycfeijfx FOREIGN KEY (RECORD_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_LIST_DELIM_DESC_T
    ADD CONSTRAINT FKt380u3n3bo4jfq7ugr1xovqqi FOREIGN KEY (DELIM_DESC_ID) REFERENCES SCORM_DELIMIT_DESC_T (DELIM_DESC_ID);

ALTER TABLE SCORM_LIST_BINDINGS_T
    ADD CONSTRAINT FKtgeta6m8u88ogvop4hkbt4qmm FOREIGN KEY (ELEMENT_ID) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_ELEMENT_T
    ADD CONSTRAINT FKtmfmx4swa611msqjx864cldsn FOREIGN KEY (PARENT) REFERENCES SCORM_ELEMENT_T (ELEMENT_ID);

ALTER TABLE SCORM_MAP_SCO_DATAMANAGER_T
    ADD CONSTRAINT FKtr8ol52ol0bfrc39jc95nisg4 FOREIGN KEY (ATTEMPT_ID) REFERENCES SCORM_ATTEMPT_T (ATTEMPT_ID);

INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.configure');
INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.delete');
INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.grade');
INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.launch');
INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.upload');
INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.validate');
INSERT INTO SAKAI_REALM_FUNCTION VALUES (DEFAULT, 'scorm.view.results');

INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'access'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.launch'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.configure'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.delete'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.grade'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.launch'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.upload'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.validate'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'maintain'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.view.results'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.configure'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.delete'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.grade'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.launch'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.upload'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.validate'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Instructor'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.view.results'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Student'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.launch'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.configure'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.delete'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.grade'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.launch'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.upload'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.validate'));
INSERT INTO SAKAI_REALM_RL_FN VALUES((select REALM_KEY from SAKAI_REALM where REALM_ID = '!site.template.course'), (select ROLE_KEY from SAKAI_REALM_ROLE where ROLE_NAME = 'Teaching Assistant'), (select FUNCTION_KEY from SAKAI_REALM_FUNCTION where FUNCTION_NAME = 'scorm.view.results'));
-- END SAK-50200

-- SAK-44945
CREATE TABLE lti_tool_site
(
    id         INT AUTO_INCREMENT NOT NULL,
    tool_id    INT DEFAULT NULL,
    SITE_ID    VARCHAR(99) NULL,
    notes      VARCHAR(1024) NULL,
    created_at datetime(0) NOT NULL,
    updated_at datetime(0) NOT NULL,
    CONSTRAINT PK_LTI_TOOL_SITE PRIMARY KEY (id)
);
-- END SAK-44945

-- SAK-48986
ALTER TABLE USER_NOTIFICATIONS ADD TOOL VARCHAR(99) NULL;
-- END SAK-48986

-- SAK-50378
ALTER TABLE lti_tools ADD lti13_lms_deployment_id VARCHAR(1024) NULL;
-- END SAK-50378

-- SAK-50846 --
ALTER TABLE SST_PRESENCES ADD CURRENT_OPEN_SESSIONS INT DEFAULT 0 NOT NULL;
-- END SAK-50846 --

-- SAK-51224
ALTER TABLE CONV_TOPICS ADD GRADED BIT NULL;
-- END SAK-51224

-- SAK-50610
ALTER TABLE CONV_TOPICS ADD GRADING_ITEM_ID BIGINT DEFAULT NULL;
-- END SAK-50610

-- SAK-51518
ALTER TABLE CONV_TOPIC_TAGS ADD CONSTRAINT UK_TOPIC_TAG UNIQUE (TOPIC_ID, TAG);
DROP INDEX FKrmek6b1bqs2jghppp27ph2dn9 ON CONV_TOPIC_TAGS;
-- END SAK-51518

-- S2U-39
ALTER TABLE rwikipagegroups ADD CONSTRAINT FKivja8wasbixfd4v4tuq69ve66 FOREIGN KEY (rwikiobjectid) REFERENCES rwikiobject (id);
CREATE INDEX FKivja8wasbixfd4v4tuq69ve66 ON rwikipagegroups(rwikiobjectid);
-- END S2U-39

-- SAK-49854
ALTER TABLE PLUS_SUBJECT MODIFY EMAIL VARCHAR(255);
ALTER TABLE PLUS_SUBJECT MODIFY SUBJECT VARCHAR(99) NOT NULL;
ALTER TABLE PLUS_SUBJECT ALTER SUBJECT DROP DEFAULT;
CREATE INDEX IDX1vblod9vyvx4cqrtq8bb1xtgo ON PLUS_SUBJECT(SUBJECT, TENANT_GUID);
CREATE INDEX IDX3q6wwy8gn0nhly8y30culvttv ON PLUS_SUBJECT(EMAIL, TENANT_GUID);
CREATE INDEX IDXda38aepc6bamrvj3xjicuuwjo ON PLUS_SUBJECT(SAKAI_USER_ID, TENANT_GUID);
-- END SAK-49854

-- SAK-50165
ALTER TABLE PLUS_TENANT DROP COLUMN NEW_WINDOW_TOOLS;
ALTER TABLE PLUS_TENANT DROP COLUMN ALLOWED_TOOLS;
-- END SAK-50165

-- SAK-49581
ALTER TABLE SAM_QUESTIONPOOLACCESS_T
    ADD CONSTRAINT FK6s27ftmf0vn279b7bydsnvwjd FOREIGN KEY (QUESTIONPOOLID) REFERENCES SAM_QUESTIONPOOL_T (QUESTIONPOOLID);
-- END SAK-49581

-- SAK-50724
ALTER TABLE rbc_rubric MODIFY created datetime(6) NOT NULL;
ALTER TABLE rbc_rubric ALTER created DROP DEFAULT;
ALTER TABLE rbc_rubric MODIFY creatorId VARCHAR(99) NOT NULL;
ALTER TABLE rbc_rubric ALTER creatorId DROP DEFAULT;
ALTER TABLE rbc_rubric MODIFY ownerId VARCHAR(99) NOT NULL;
ALTER TABLE rbc_rubric ALTER ownerId DROP DEFAULT;
ALTER TABLE rbc_rubric MODIFY title VARCHAR(255) NOT NULL;
ALTER TABLE rbc_rubric ALTER title DROP DEFAULT;
-- END SAK-50724
