-- Begin SAK-50526
ALTER TABLE CONV_TOPICS ADD UPVOTES NUMBER(10) DEFAULT 0;
ALTER TABLE CONV_TOPIC_STATUS ADD UPVOTED NUMBER(1) DEFAULT 0;
ALTER TABLE CONV_POSTS ADD (
  NUMBER_OF_THREAD_UPVOTES NUMBER(10) DEFAULT 0,
  REACTION_COUNT NUMBER(10) DEFAULT 0
);
DELETE FROM CONV_POST_REACTIONS WHERE reaction >= 4;
-- End SAK-50526
