-- SAK-46436
ALTER TABLE TASKS ADD TASK_OWNER VARCHAR2(99 CHAR);

CREATE TABLE TASKS_ASSIGNED
(
   ID              NUMBER(19,0) NOT NULL,
   TASK_ID         NUMBER(19,0) NOT NULL,
   ASSIGNATION_TYPE   VARCHAR2(5) NOT NULL,
   OBJECT_ID       VARCHAR2(99 CHAR),
   PRIMARY KEY(ID),
   CONSTRAINT FK_TASKS_ASSIGNED_TASKS FOREIGN KEY(TASK_ID) REFERENCES TASKS (ID)
);

CREATE SEQUENCE TASKS_ASSIGNED_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
CREATE INDEX IDX_TASKS_ASSIGNED ON TASKS_ASSIGNED (TASK_ID);