-- SAK-41207 Add indexes
CREATE INDEX UK_hyk73ocki8gwvm3ajf8ls08ac ON ASN_ASSIGNMENT_ATTACHMENTS (ASSIGNMENT_ID);
CREATE INDEX UK_8ewbxsplke3c487h0tjujvtm ON ASN_ASSIGNMENT_GROUPS (ASSIGNMENT_ID);
CREATE INDEX UK_jg017qxc4pv3mdf07c1xpytb8 ON ASN_SUBMISSION_ATTACHMENTS (SUBMISSION_ID);
CREATE INDEX UK_3dou5gsqcya4rwwy99l91fofb ON ASN_SUBMISSION_FEEDBACK_ATTACH (SUBMISSION_ID);
-- END SAK-41207
