-- clear unchanged bundle properties
DELETE SAKAI_MESSAGE_BUNDLE from SAKAI_MESSAGE_BUNDLE where PROP_VALUE is NULL;

-- this constraint may have been missed, it is ok if this line fails just comment it out
ALTER TABLE CONTENTREVIEW_ITEM ADD CONSTRAINT UK_8dngr1v68kkv4u11c1nvrjj1l UNIQUE (PROVIDERID, CONTENTID);

-- SAK-30079
ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY COLUMN AUTO_FORWARD INT NOT NULL DEFAULT 2;

-- SAK-43826 : Rubrics: Support weighted criterions

ALTER TABLE rbc_rubric ADD weighted BIT NOT NULL;
ALTER TABLE rbc_criterion ADD weight FLOAT DEFAULT 0 NULL;

-- SAK-44637 - Make the Lessons Placement checkbox work
-- Note that SAK-44636 already added the column in sakai_20_1-20_2_mysql_conversion.sql
-- It is included here and commented out in case you need it.
ALTER TABLE lti_tools ADD pl_lessonsselection TINYINT DEFAULT 0;
-- Existing records needed to be switched on right before the feature is used
UPDATE lti_tools SET pl_lessonsselection = 1;
-- END SAK-44637

-- SAK-44810 - Add $Resource.id.history
-- This needs to rename a column in the DB because of a bug that keeps "settings"
-- from working as needed for this feature.
-- MySQL >= 8.0
-- ALTER TABLE lti_tools RENAME COLUMN allowsettings TO allowsettings_ext;
-- MySQL <= 8.0
ALTER TABLE lti_tools CHANGE allowsettings allowsettings_ext TINYINT DEFAULT 0;
-- If autoDDL somehow already ran and created allowsettings_ext - then you need
-- to copy data from the old column and delete it
-- UPDATE lti_tools SET allowsettings_ext=allowsettings;
-- ALTER TABLE lti_tools DROP COLUMN allowsettings;
-- END SAK-44810 

-- SAK-45174 Rubrics metadata datetime conversion
ALTER TABLE rbc_criterion DROP created;
ALTER TABLE rbc_criterion DROP modified;
ALTER TABLE rbc_evaluation DROP created;
ALTER TABLE rbc_evaluation DROP modified;
ALTER TABLE rbc_rating DROP created;
ALTER TABLE rbc_rating DROP modified;
ALTER TABLE rbc_rubric DROP created;
ALTER TABLE rbc_rubric DROP modified;
ALTER TABLE rbc_tool_item_rbc_assoc DROP created;
ALTER TABLE rbc_tool_item_rbc_assoc DROP modified;

ALTER TABLE rbc_criterion ADD created DATETIME NULL;
ALTER TABLE rbc_criterion ADD modified DATETIME NULL;
ALTER TABLE rbc_evaluation ADD created DATETIME NULL;
ALTER TABLE rbc_evaluation ADD modified DATETIME NULL;
ALTER TABLE rbc_rating ADD created DATETIME NULL;
ALTER TABLE rbc_rating ADD modified DATETIME NULL;
ALTER TABLE rbc_rubric ADD created DATETIME NULL;
ALTER TABLE rbc_rubric ADD modified DATETIME NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD created DATETIME NULL;
ALTER TABLE rbc_tool_item_rbc_assoc ADD modified DATETIME NULL;

UPDATE rbc_criterion SET created = NOW() WHERE created IS NULL;
UPDATE rbc_criterion SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_evaluation SET created = NOW() WHERE created IS NULL;
UPDATE rbc_evaluation SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_rating SET created = NOW() WHERE created IS NULL;
UPDATE rbc_rating SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_rubric SET created = NOW() WHERE created IS NULL;
UPDATE rbc_rubric SET modified = NOW() WHERE modified IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET created = NOW() WHERE created IS NULL;
UPDATE rbc_tool_item_rbc_assoc SET modified = NOW() WHERE modified IS NULL;
-- END SAK-45174

-- SAK-44019
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_ID INT DEFAULT null NULL;
ALTER TABLE ASN_ASSIGNMENT ADD CONTENT_LAUNCH_NEW_WINDOW BIT DEFAULT 0 NULL;
-- END SAK-44019

-- SAK-41502
ALTER TABLE GB_GRADING_EVENT_T ADD IS_EXCLUDED INT NOT NULL DEFAULT 0;
-- END SAK-41502

-- SAK-45184
CREATE TABLE FILE_CONVERSION_QUEUE (
    ID                   BIGINT       AUTO_INCREMENT PRIMARY KEY,
    ATTEMPTS             INT          NOT NULL,
    LAST_ATTEMPT_STARTED DATETIME     NULL,
    REFERENCE            VARCHAR(255) NOT NULL,
    STATUS               VARCHAR(16)  NOT NULL
);

CREATE INDEX IDX_FCI_REF_TYPE ON FILE_CONVERSION_QUEUE (REFERENCE);

create table MFR_DRAFT_RECIPIENT_T (
    ID           BIGINT           AUTO_INCREMENT PRIMARY KEY,
    BCC          BIT DEFAULT B'0' NOT NULL,
    DRAFT_ID     BIGINT           NOT NULL,
    RECIPIENT_ID VARCHAR(255)     NOT NULL,
    TYPE         INT              NOT NULL
);

CREATE INDEX MFR_DRAFT_REC_MSG_ID_I ON MFR_DRAFT_RECIPIENT_T (DRAFT_ID);

create table TASKS (
    ID          BIGINT       AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    DUE         DATETIME     NULL,
    REFERENCE   VARCHAR(255) NOT NULL,
    SITE_ID     VARCHAR(99)  NULL,
    STARTS      DATETIME     NULL,
    SYSTEM      BIT          NOT NULL
);

CREATE INDEX IDX_TASKS_REF_TYPE ON TASKS (REFERENCE);

create table USER_TASKS (
    ID           BIGINT      AUTO_INCREMENT PRIMARY KEY,
    COMPLETE     BIT         NULL,
    NOTES        LONGTEXT    NULL,
    PRIORITY     INT         NOT NULL,
    SOFT_DELETED BIT         NULL,
    USER_ID      VARCHAR(99) NOT NULL,
    TASK_ID      BIGINT      NOT NULL,
    CONSTRAINT FKmj3lsh7wx4o7s7i6hy80tbpsn FOREIGN KEY (TASK_ID) REFERENCES TASKS (ID)
);

CREATE INDEX IDX_USER_TASK ON USER_TASKS (USER_ID, TASK_ID);

ALTER TABLE rbc_tool_item_rbc_assoc ADD active BIT NOT NULL DEFAULT 1;

ALTER TABLE rbc_tool_item_rbc_assoc DROP KEY UK_q4btc0dfymi80bb5mp3vp3r7u;

CREATE INDEX FK1yhjvx9pxp5e76ijo0s6ahvsa ON rbc_tool_item_rbc_assoc(rubric_id);

ALTER TABLE rbc_tool_item_rbc_assoc DROP KEY UKq4btc0dfymi80bb5mp3vp3r7u;

DROP INDEX contentreview_provider_id_idx ON CONTENTREVIEW_ITEM;

CREATE INDEX contentreview_provider_id_idx ON CONTENTREVIEW_ITEM(EXTERNALID);

-- LTI
ALTER TABLE lti_content ADD `description` MEDIUMTEXT NULL;
ALTER TABLE lti_content ADD protect TINYINT DEFAULT 0 NULL;
ALTER TABLE lti_content DROP COLUMN sha256;
ALTER TABLE lti_tools ADD pl_privacy TINYINT DEFAULT 0 NULL;
ALTER TABLE lti_tools ADD pl_coursenav TINYINT DEFAULT 0 NULL;
ALTER TABLE lti_tools ADD lti13_auto_token VARCHAR(1024) NULL;
ALTER TABLE lti_tools ADD lti13_auto_state INT DEFAULT null NULL;
ALTER TABLE lti_tools ADD lti13_auto_registration MEDIUMTEXT NULL;
ALTER TABLE lti_tools MODIFY lti13_tool_keyset VARCHAR(1024);
ALTER TABLE lti_tools DROP COLUMN lti13_tool_kid;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_private;
ALTER TABLE lti_tools DROP COLUMN lti13_tool_public;
ALTER TABLE lti_tools DROP COLUMN sha256;


ALTER TABLE SAKAI_PERSON_T MODIFY PHONETIC_PRONUNCIATION VARCHAR(255);


ALTER TABLE MFR_PRIVATE_FORUM_T MODIFY AUTO_FORWARD INT;
ALTER TABLE MFR_PRIVATE_FORUM_T ALTER AUTO_FORWARD SET DEFAULT null;
DROP INDEX MFR_UNREAD_STATUS_I1 ON MFR_UNREAD_STATUS_T;
CREATE INDEX MFR_UNREAD_STATUS_I1 ON MFR_UNREAD_STATUS_T(TOPIC_C);


-- Polls
ALTER TABLE POLL_OPTION MODIFY DELETED BIT(1) NOT NULL;
ALTER TABLE POLL_OPTION ALTER DELETED SET DEFAULT 0;
ALTER TABLE POLL_OPTION MODIFY OPTION_ORDER INT NOT NULL;
ALTER TABLE POLL_OPTION ALTER OPTION_ORDER DROP DEFAULT;
ALTER TABLE POLL_OPTION MODIFY OPTION_POLL_ID BIGINT NOT NULL;
ALTER TABLE POLL_OPTION ALTER OPTION_POLL_ID DROP DEFAULT;
ALTER TABLE POLL_OPTION MODIFY OPTION_TEXT LONGTEXT NOT NULL;
ALTER TABLE POLL_OPTION MODIFY OPTION_UUID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_OPTION ALTER OPTION_UUID DROP DEFAULT;

ALTER TABLE POLL_POLL MODIFY POLL_CREATION_DATE datetime NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_CREATION_DATE DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_DISPLAY_RESULT VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_DISPLAY_RESULT DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_IS_PUBLIC BIT(1) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_IS_PUBLIC DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_LIMIT_VOTE BIT(1) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_LIMIT_VOTE DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_MAX_OPTIONS INT NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_MAX_OPTIONS DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_MIN_OPTIONS INT NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_MIN_OPTIONS DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_OWNER VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_OWNER DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_SITE_ID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_SITE_ID DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_TEXT LONGTEXT NOT NULL;
ALTER TABLE POLL_POLL MODIFY POLL_UUID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_UUID DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_CLOSE datetime NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_VOTE_CLOSE DROP DEFAULT;
ALTER TABLE POLL_POLL MODIFY POLL_VOTE_OPEN datetime NOT NULL;
ALTER TABLE POLL_POLL ALTER POLL_VOTE_OPEN DROP DEFAULT;

ALTER TABLE POLL_VOTE MODIFY VOTE_DATE datetime NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_DATE DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY VOTE_IP VARCHAR(255) NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_IP DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY VOTE_POLL_ID BIGINT NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_POLL_ID DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY VOTE_SUBMISSION_ID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_VOTE ALTER VOTE_SUBMISSION_ID DROP DEFAULT;
ALTER TABLE POLL_VOTE MODIFY USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE POLL_VOTE ALTER USER_ID DROP DEFAULT;


-- Site Setup Questions
ALTER TABLE SSQ_ANSWER MODIFY ANSWER VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_ANSWER ALTER ANSWER DROP DEFAULT;
ALTER TABLE SSQ_ANSWER MODIFY FILL_IN_BLANK BIT(1) NOT NULL;
ALTER TABLE SSQ_ANSWER ALTER FILL_IN_BLANK DROP DEFAULT;
ALTER TABLE SSQ_ANSWER MODIFY ORDER_NUM INT NOT NULL;
ALTER TABLE SSQ_ANSWER ALTER ORDER_NUM DROP DEFAULT;

ALTER TABLE SSQ_QUESTION MODIFY IS_CURRENT VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER IS_CURRENT DROP DEFAULT;
ALTER TABLE SSQ_QUESTION MODIFY MULTIPLE_ANSWERS BIT(1) NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER MULTIPLE_ANSWERS DROP DEFAULT;
ALTER TABLE SSQ_QUESTION MODIFY ORDER_NUM INT NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER ORDER_NUM DROP DEFAULT;
ALTER TABLE SSQ_QUESTION MODIFY REQUIRED BIT(1) NOT NULL;
ALTER TABLE SSQ_QUESTION ALTER REQUIRED DROP DEFAULT;

ALTER TABLE SSQ_USER_ANSWER MODIFY SITE_ID VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_USER_ANSWER ALTER SITE_ID DROP DEFAULT;
ALTER TABLE SSQ_USER_ANSWER MODIFY USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_USER_ANSWER ALTER USER_ID DROP DEFAULT;

ALTER TABLE SSQ_SITETYPE_QUESTIONS MODIFY SITE_TYPE VARCHAR(255) NOT NULL;
ALTER TABLE SSQ_SITETYPE_QUESTIONS ALTER SITE_TYPE DROP DEFAULT;

-- END SAK-45184

-- START SAK-42371
ALTER TABLE rbc_evaluation ADD status INT NOT NULL;
UPDATE rbc_evaluation SET status = 2;
-- END SAK-42371

