-- clear unchanged bundle properties
DELETE from SAKAI_MESSAGE_BUNDLE where PROP_VALUE is NULL;

-- SAK-43826 : Rubrics: Support weighted criterions

ALTER TABLE RBC_RUBRIC ADD WEIGHTED NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE RBC_CRITERION ADD WEIGHT DOUBLE PRECISION DEFAULT 0 NOT NULL;
