-- SAK-40427
UPDATE SAKAI_SITE_TOOL SET TITLE = 'Discussions' WHERE REGISTRATION = 'sakai.forums' AND TITLE = 'Forums';
UPDATE SAKAI_SITE_PAGE SET TITLE = 'Discussions' WHERE TITLE = 'Forums';
-- End SAK-40427

-- SAK-44305
create table MFR_DRAFT_RECIPIENT_T
(ID bigint not null auto_increment,
 TYPE int not null,
 RECIPIENT_ID varchar(255) not null,
 DRAFT_MSG_ID bigint not null,
 BCC bit not null,
 primary key (ID));

create index MFR_DRAFT_REC_MSG_ID_I on MFR_DRAFT_RECIPIENT_T(DRAFT_MSG_ID);
-- End SAK-44305

-- SAK-45565
ALTER TABLE lesson_builder_groups CHANGE COLUMN `groups` item_groups LONGTEXT NULL DEFAULT NULL;
ALTER TABLE tasks CHANGE COLUMN `SYSTEM` SYSTEM_TASK BIT(1) NOT NULL;
-- SAK-45565

-- SAK-44967
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN ALLOW_COMPARE_GRADES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_GRADES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_FIRSTNAMES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_SURNAMES BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_COMMENTS BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_DISPLAY_ALLITEMS BIT(1) DEFAULT FALSE NOT NULL;
ALTER TABLE GB_GRADEBOOK_T ADD COLUMN COMPARING_RANDOMIZEDATA BIT(1) DEFAULT FALSE NOT NULL;
-- End SAK-44967

-- SAK-43155
ALTER TABLE ASN_ASSIGNMENT ADD IS_REQUIRED_ESTIMATE CHAR(1) NULL;
ALTER TABLE ASN_ASSIGNMENT ADD ESTIMATE VARCHAR(255) NULL;
ALTER TABLE ASN_SUBMISSION_SUBMITTER ADD TIME_SPENT VARCHAR(255) NULL;
ALTER TABLE ASN_ASSIGNMENT ADD CONSTRAINT CHECK_IS_REQUIRED_ESTIMATE CHECK (IS_REQUIRED_ESTIMATE IN ('0', '1'));

CREATE TABLE ASN_TIMESHEET (
ID BIGINT(20) NOT NULL AUTO_INCREMENT,
SUBMITTER_ID BIGINT(20) NOT NULL,
REG_DATE DATETIME NOT NULL,
REG_TIME VARCHAR(255) NOT NULL,
ASN_COMMENT VARCHAR(500) NULL,
PRIMARY KEY (ID),
CONSTRAINT FK_ASN_SUBMISSION_SUB_TEST FOREIGN KEY (SUBMITTER_ID) REFERENCES ASN_SUBMISSION_SUBMITTER (ID)
);
-- End SAK-43155

