-- Begin SAK-50526
ALTER TABLE CONV_TOPICS ADD COLUMN UPVOTES int NULL DEFAULT 0;
ALTER TABLE CONV_TOPIC_STATUS ADD COLUMN UPVOTED bit(1) NULL DEFAULT b'0';
ALTER TABLE CONV_POSTS
  ADD COLUMN NUMBER_OF_THREAD_UPVOTES int NULL DEFAULT 0,
  ADD COLUMN REACTION_COUNT int NULL DEFAULT 0 AFTER;
-- End SAK-50526
