-- SAK-46157

-- Missing foreign key indexes
CREATE INDEX FK_CON_REVIEW_ITEM_I ON CONTENTREVIEW_ITEM_PROPERTIES (CONTENTREVIEW_ITEM_ID);
CREATE INDEX FK_ASN_ASSIGMENTS_PROP_I ON ASN_ASSIGNMENT_PROPERTIES (ASSIGNMENT_ID);
CREATE INDEX FK_ASN_ASSIGMENTS_SUB_I ON ASN_SUBMISSION (ASSIGNMENT_ID);
CREATE INDEX FK_ASN_SUBMISSION_PROP ON ASN_SUBMISSION_PROPERTIES (SUBMISSION_ID);
CREATE INDEX FK_ASN_SUBMISSION_SUB_I ON ASN_SUBMISSION_SUBMITTER (SUBMISSION_ID);
CREATE INDEX FK_6jo83t1ddebdbt9296y1xftkn ON rbc_rubric_criterions (rbc_rubric_id);
CREATE INDEX FK_faohmo8ewmybgp67w10g53dtm ON rbc_evaluation (association_id);
CREATE INDEX FK_h4u89cj06chitnt3vcdsu5t7m ON rbc_criterion_ratings (rbc_criterion_id);
CREATE INDEX FK_rdpid6jl4csvfv6la80ppu6p9 ON rbc_tool_item_rbc_assoc_conf (association_id);
CREATE INDEX FK_SAK_REALM_LOCK_KEY_I ON SAKAI_REALM_LOCKS (REALM_KEY);
CREATE INDEX GB_GRADABLE_OBJ_CT_IDX ON GB_GRADABLE_OBJECT_T (CATEGORY_ID);
CREATE INDEX GB_CATEGORY_GB_INDX ON GB_CATEGORY_T (GRADEBOOK_ID);
CREATE INDEX FK_GB_COMMENT_GB_OBJ_ID_I ON GB_COMMENT_T (GRADABLE_OBJECT_ID);
CREATE INDEX FK_GB_SEL_GRADE_MAP_I ON GB_GRADEBOOK_T (SELECTED_GRADE_MAPPING_ID);
CREATE INDEX FK_GB_GRADE_MAP_SCALE_I ON GB_GRADE_MAP_T (GB_GRADING_SCALE_T);
CREATE INDEX FK_GB_SPRD_GRADEBOOK_I ON GB_SPREADSHEET_T (GRADEBOOK_ID);
CREATE INDEX FK_SAM_ATTACH_ASSESSMENT_I ON SAM_ATTACHMENT_T (ASSESSMENTID);
CREATE INDEX FK_SAM_ATTACH_ITEM_I ON SAM_ATTACHMENT_T (ITEMID);
CREATE INDEX FK_SAM_ATTACH_SECTION_I ON SAM_ATTACHMENT_T (SECTIONID);
CREATE INDEX FK_SAM_FAV_CHOICE_I ON SAM_FAVORITECOLCHOICESITEM_T (FAVORITEID);
CREATE INDEX FK_SAM_GRADE_ATTACH_ASSESS_I ON SAM_GRADINGATTACHMENT_T (ASSESSMENTGRADINGID);
CREATE INDEX FK_SAM_GRADE_ATTACH_ITEM_I ON SAM_GRADINGATTACHMENT_T (ITEMGRADINGID);
CREATE INDEX FK_SAM_GRADE_SUM_ASSESSMENT_I ON SAM_GRADINGSUMMARY_T (PUBLISHEDASSESSMENTID);
CREATE INDEX FK_SAM_MEDIA_ITEM_I ON SAM_MEDIA_T (ITEMGRADINGID);
CREATE INDEX FK_SAM_PUB_ATTACH_ITEM_I ON SAM_PUBLISHEDATTACHMENT_T (ITEMID);

-- end SAK-46157

-- START SAK-44489
CREATE SEQUENCE BULLHORN_ALERTS_S MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
-- END SAK-44489
