
-- START SAK-51950
CREATE INDEX CALENDAR_EVENT_CID_RSTART_REND_ESTART
  ON CALENDAR_EVENT (CALENDAR_ID, RANGE_START, RANGE_END, EVENT_START);
-- END SAK-51950

-- START SAK-49313
ALTER TABLE SAM_PUBLISHEDASSESSMENT_T MODIFY COMMENTS VARCHAR(4000) NULL;
-- END SAK-49313

