-- SAK-41878
CREATE INDEX UK_f0kvf8pq0xapndnamvw5xr2ib ON ASN_SUBMISSION_SUBMITTER (SUBMITTER);
-- SAK-41878

-- SAK-41841
ALTER TABLE RBC_CRITERION_OUTCOME ADD COMMENTS_COPY VARCHAR2(255);
UPDATE RBC_CRITERION_OUTCOME SET COMMENTS_COPY = COMMENTS;
UPDATE RBC_CRITERION_OUTCOME SET COMMENTS = NULL;
ALTER TABLE RBC_CRITERION_OUTCOME MODIFY COMMENTS LONG;
ALTER TABLE RBC_CRITERION_OUTCOME MODIFY COMMENTS CLOB;
UPDATE RBC_CRITERION_OUTCOME SET COMMENTS = COMMENTS_COPY;
ALTER TABLE RBC_CRITERION_OUTCOME DROP COLUMN COMMENTS_COPY;
-- SAK-41841